corona-warn-app/cwa-website

- src/data/index_de.json
The link for all news is broken in slider on German page. It points to https://www.coronawarn.app/de/news/, but it should be https://www.coronawarn.app/de/aktuelles/.
> Fix link for all news in slider on German page

- package.json
The repository is flagged to be licensed under `Apache v2`, but the license in the `package.json` is set to `MIT`. Although the package is not published, this looks quite odd and should be fixed.
> align package.json with the repository license

- src/data/faq_de.json
1. Better language
2. Germanization of "cyber security" to "Cyber-Security" analogous to other English double and triple words in this text, such as "GitHub-Repositories", "Corona-Warn-App" etc.
> Minor fixes in faq_de.json

- src/data/faq.json
- src/data/faq_de.json
The question is about who will operate the backend of the app according to issue [cwa-documentation/173](https://github.com/corona-warn-app/cwa-documentation/issues/173).
> Add a question to the FAQ

- README.md
This change adds a badge for Mozilla's Observatory status to display the website's security status discussed in #6.
> display Mozillas Obersovatory status

- src/root-assets/robots.txt
Fix the issue #21 (Remove duplicate content from robots.txt)
Remove the not necessary declaration from /sitemap.htm
> remove not necessary declaration

- src/partials/button-link-component.html
- src/partials/error-page-content.html
There are duplicated span-tag, which cause errors on w3c validator.
https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.coronawarn.app%2Fde%2F
> fix duplicated span-tag

- src/data/index_de.json
Avoid the (incorrect) impression that cwa-server keeps a list of infected _persons_.
> Avoid the word "person" in connection with cwa-server 

- src/assets/js/redirect.js
- src/layouts/redirect.html
- src/pages/index.html
The inline script is nonsence because of the Content-Security-Policy. It prints out a warning and redirects to the english version via meta at any time. 
`Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' *.coronawarn.app". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`
The javascript did not work on any of my browsers. But of curse, I neither use Safari nor Internet Explorer
> Redirect to german page when lang_de is set

- src/data/faq_de.json
The sentence contains two verbs, one of which is probably from a previous version of that sentence:
> ..., unterstützt sie die energieeffiziente Bluetooth-Technologie BLE (Bluetooth Low Energy) ~verwenden~.
> [trivial] Remove superfluous verb from sentence

- src/data/faq.json
"und" has been changed to "and" in one of the questions
> FAQ EN: small typo

- src/data/community.json
Acute accent switched to an apostrophe.
https://www.cl.cam.ac.uk/~mgk25/ucs/apostrophe.html
> Fix apostrophe error

- src/data/community.json
Minor language tweak. It would be a little strange asking someone to bring you somewhere. Asking someone to take you somewhere makes a little more sense. 
You wouldn't ask a taxi driver to bring you somewhere, for example, but to take you to your destination.
> Change "Bring me to GitHub" -> "Take me to GitHub"

- src/data/faq.json
- src/data/faq_de.json
Added new question: "Apple: In den Einstellungen für das COVID-19-Kontaktprotokoll steht: „Corona-Warn hat dein Protokoll mit erfassten zufälligen IDs während der letzten 24 Stunden 0-mal überprüft“. Funktioniert die Risiko-Ermittlung nicht?" / "Apple: In my COVID-19 Exposure Logging settings it says: “Corona-Warn has checked your log of collected random IDs 0 times over the past 24 hours.” Does this mean that exposure logging isn’t working?"
> FAQ (EN+DE): New question about exposure log not being checked

- gulpfile.js
It should be config, since it actually loaded from config.yml not settings.yml which is confusing
> Correcting comment

- src/assets/scss/_type.scss
- src/data/index.json
- src/data/index_de.json
This fixes two errors reported by https://validator.w3.org/.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Replace deprecated nobr tag by CSS (fix W3C errors)

- src/partials/page-faq.html
> faq: remove unnecessary class name from deeplinks

- src/assets/js/app.js
- src/partials/text-component.html
This resolves #128.
For all headline text elements containing an id, the location hash will be updated once this element reaches the top of the screen when scrolling.
Whenever the location hash changes, whether through the scroll listener or through a click on the FAQ sidebar menu, the active item in the menu will be updated accordingly.
If there is a hash set on page load, an initial 'hashchange' is fired to ensure the menu state is correct.
> Update scroll menu active item

- src/assets/scss/_header.scss
GitHub icon in navigation had irregular margin / distance. Added `margin-right`
> Fix margin on GitHub icon in top navigation

- src/assets/scss/_variables.scss
_this fixes #93_ 
and increeses the lighthouse score!
Lighthouse requires a color contrast ration of >7. The current value is 3.38.
I'll changed the clolor `blue` to be above 7 (Level AAA) - and still look good :wink:. 
see [TR/WCAG21#contrast-minimum](https://www.w3.org/TR/WCAG21/#contrast-minimum)
> accessibility: increase color contrast ratio to >7

- src/data/faq.json
- src/data/faq_de.json
> FAQ (EN/DE): remove 'project' from headline title

- src/assets/scss/_nav.scss
- src/data/faq_de.json
- src/partials/page-faq.html
- src/partials/text-component.html
Using &shy; at the proper point in the string avoids that it will overlap the real FAQ text on mobile devices.
To render that properly, triple curly brackets needed to be introduced for two strings.
> Soft Hyphen to avoid overlapping FAQ section navigation (closes #217)

- src/data/faq.json
- src/data/faq_de.json
Fixing double highlighting on deep links by not activating both top nav entries.
Note to future self: Fix this the right way by altering the scrolling behavior which expects only a single item to be selected at all times ... or by enforcing that only a single item is selected at all times.
> Prevent Double Highlighting

- src/assets/js/app.js
Instead of matching the entire string, now every word is looked up and if they all appear in the answer, it is returned.
Previous: "Google log" would yield no result
Now:"Google log" yields all FAQ entries containing `google` and `log`
> Better Search

- src/assets/scss/_faq.scss
- src/assets/scss/style.scss
- src/partials/page-faq.html
Turns out that apple zooms in on inputs that have a font size smaller than 16px
Hence, this PR cleans up the faq-search input and assigns a proper font size. This prevents the annoying zoom-in when entering texts.
> Fixing annoying zoom on mobile devices (closes #287)

- src/assets/js/static/faq-redirect.js
- src/pages/de/faq/(39508).html
- src/pages/en/faq/(39508).html
- src/partials/faq-redirect.html
It seems the URL for the error message of the 39508 error is wrong within the app (https://github.com/corona-warn-app/cwa-app-android/issues/1021).
This PR **mitigates** that by taking the wrong link and redirecting to the proper FAQ entry. 
This should not be a long-living solution. If the link in the app is fixed, remove the two `(39508).html` files (I'll create a separate issue as a reminder). You can keep the faq-redirect.js and faq-redirect.html files just in case ^^
> Mitigate wrong links in app error message

- src/data/faq.json
The FAQ mentions Matched Key Count (Android), when Matched Key Count is a term used by iOS.
I would have chosen the word "iOS", but "Apple" is already used in a similar case immediately above for `Provided Key Count`.
Closes #304
> Change "Android" to "Apple"

- src/helpers/blogentries.js
- src/services/blog-processor.js
Currently the redirects are represented as "undefined" entries. This PR removes them from the overview while leaving the list intact.
> Remove redirects from Blog List

- gulpfile.js
- src/assets/js/app.js
Before, the JS would check the url path for the language and then determine which file to download. Now, it only expects an `faq.json` file in its folder and gulp build takes care of creating these files accordingly.
> The FAQ search JS code should not care about the language

- gulpfile.js
Currently, the FAQ texts are completely copied into the json docs that are used to do the search.
This PR removes the html tags from the text. By that, we avoid showing results that do not *visibly* contain the respective search string.
> Remove HTML Tags from searchable FAQ

- src/assets/js/app.js
Searching a query with one parenthesis led to an uncaught unterminated parenthetical SyntaxError, as JavaScript translates the parameter to RegExp.
> If a non-RegExp object regexp is passed, it is implicitly converted to a RegExp with new RegExp(regexp). [(source)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search)
However, this disables the possibility of using RegExp to filter the items.
> fixed regexp errors

- src/data/faq.json
- src/data/faq_de.json
Update the FAQ to explain that iOS 14 Beta is not supported, regardless of the Beta version. Further discussion on this topic was on the issue #340
> Updated the FAQ according to #340

- src/data/faq_de.json
closes: #367 
This PR corrects the gramma Mistake in the German FAQ regarding the iOS 14 Beta. Please see #367 for more information.
@mtb77 Could you review and merge it? Thanks!
> Correct gramma Mistake in the German FAQ

- src/data/index.json
- src/data/index_de.json
The Main Page is still showing that the newest CWA version is 1.2.1 and the newest iOS version is 13.6.
Updated this to show the latest information.
Added "at least"/"mindestens" before the Android version to make clearer that Android 6 isn't the newest Android version.
Please make sure I've got everything correct and feel free to edit something. @mtb77 @svengabr
> Update main page

- src/data/faq.json
- src/data/faq_de.json
> Risk exposure can no longer be activated after updating to iOS 14

- gulpfile.js
https://apps.apple.com/de/app/corona-warn-app/id1512595757 lists iOS version 1.5.2 with date Oct 26, 2020.
https://play.google.com/store/apps/details?id=de.rki.coronawarnapp lists Android version 1.5.1 with date Oct 26, 2020.
> Update iOS version to 1.5.2 and Android version to 1.5.1

- src/data/faq.json
- src/data/faq_de.json
move FAQ to resolved and add text:
EN: "<b>UPDATE</b><br/>This issue has been fixed in Version 1.6.1. <hr/>"
DE: "<b>AKTUELL</b><br/>Das Problem ist in Version 1.6.1 behoben worden.<hr/>"
> FAQ website 'Exposure check failed' v1.6.0 fixed in 1.6.1

- src/data/faq.json
- src/data/faq_de.json
EN
{
"title": "[Apple/iOS] 'ExposureDetectionIsAlreadyRunning' in CWA version 1.6.1",
"anchor": "ExposureDetectionIsAlreadyRunning",
"active": true,
"textblock": [
"The notification <a href='https://github.com/corona-warn-app/cwa-app-ios/issues/1497'>'ExposureDetectionIsAlreadyRunning'</a> <a href='https://github.com/corona-warn-app/cwa-app-ios/issues/1512#issuecomment-727206633'>can be ignored</a>. The CWA is still working correctly and this issue will be solved with a <a href='https://github.com/corona-warn-app/cwa-app-ios/pull/1510'>future release</a>."
]
},
DE
{
"title": "[Apple/iOS] 'ExposureDetectionIsAlreadyRunning' in CWA version 1.6.1",
"anchor": "ExposureDetectionIsAlreadyRunning",
"active": true,
"textblock": [
"Die Meldung <a …
> FAQ website notifications new entry  ExposureDetectionIsAlreadyRunning

- src/data/faq.json
- src/data/faq_de.json
Text from RKI via @loki-cui in https://github.com/corona-warn-app/cwa-website/pull/573#issuecomment-728768274
@svengabr also involved
**Kann ich positive Testergebnisse aus anderen Ländern eingeben?**
Nein, das ist leider nicht möglich. Jedes positive Test-Ergebnis, das in die App geladen wird, muss zuvor von Laboren überprüft worden sein. Diese stellen sicher, dass kein Missbrauch stattfindet und keine falsche Ergebnisse eingetragen werden. Dazu sind zur Zeit nur Labore in Deutschland angeschlossen. Sie können also kein positives Testergebnis aus anderen Ländern, zum Beispiel aus den Niederlanden, eingeben.
**Kann ich positive Testergebnisse aus anderen Ländern in die Corona-Warn-App eingeben?**
Wenn Sie sich im EU-Ausland oder in einem [dieser …
> Allow foreign PCR tests through TAN hotline (closes #555)

- SECURITY.md
The SAP Trust Center is now reachable via https://www.sap.com/about/trust-center/security/incident-management.html (with a /security/).
At the end of the SECURITY.md the correct link is already used. Line 12 however, uses the old url.
> Fix url for SAP Trust Center

- src/data/faq_de.json
The title of the FAQ entry https://www.coronawarn.app/de/faq/#qr_scan said:
>Beim Einscannen erhalte des QR Codes ich einen Fehler.'
This is grammatically wrong so I corrected it 😅😀
> Corrected the title of `qr_scan` (German)

- gulpfile.js
This PR updates the `[minimum-required-os-version]` in the gulpfile for iOS (13.6 --> 13.7)
Source for iOS 13.7: https://apps.apple.com/de/app/corona-warn-app/id1512595757
> Update `[ios.minimum-required-os-version]` in gulpfile.js from 13.6 to 13.7

- src/data/faq.json
- src/data/faq_de.json
This PR matches the German and English text in this https://www.coronawarn.app/en/faq/#various_device_problems / https://www.coronawarn.app/de/faq/#various_device_problems FAQ entry. In the German entry the link to the Apple support was also fixed.
> Fix link  in `various_device_problems` and match German and English text

- src/data/faq_de.json
This PR removes the spurious "e" in the `cause2001` FAQ entry.
Closes #790
> Remove "e" from FAQ entry

- src/data/faq_de.json
The first typo is in "Etwas ist schief gelaufen"
The string in the app is `errors_generic_headline` and it reads
"Etwas ist schiefgelaufen."
The second typo is in the word "SIe" which should be "Sie".
(Note the file was edited with the Atom editor.)
> Correct two typos in faq/#cause2001

- src/data/faq_de.json
This PR corrects all spelling of "schief gelaufen" to "schiefgelaufen" in https://www.coronawarn.app/de/faq/ corresponding to the correction in the error message in Android app releases from 1.1.1 (released in July 2020) onwards.
The last release to use the old (incorrect) spelling was version 1.0.5.
> FAQ: Change spelling "schief gelaufen" to "schiefgelaufen" (closes #795)

- gulpfile.js
The current iOS app version is 1.12.1 and not 1.12
Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.12.1
> Update iOS version in gulpfile.js

- src/data/faq_de.json
https://www.coronawarn.app/de/faq/#rooted_devices currently includes the text
"Nein, die App wird auf **gerooten** Geräten nicht unterstützt."
This PR changes the word "gerooten" to "gerooteten" and so corrects the misspelling.
---
Proposed changed version:
> Correct typo in FAQ rooted_devices to gerooteten

- src/data/faq.json
- src/data/faq_de.json
This PR corrects a link to the RKI in the FAQ article 
https://www.coronawarn.app/de/faq/#numbers_RKI & 
https://www.coronawarn.app/en/faq/#numbers_RKI
This PR also corrects what has been previously [discussed](https://github.com/corona-warn-app/cwa-website/pull/885#issuecomment-778515262) with @dsarkar in #885.
---
Closes #886
> Fix link in `numbers_RKI` (Closes #886)

- src/data/faq.json
- src/data/faq_de.json
This PR corrects the FAQ entries:
https://www.coronawarn.app/en/faq/#exposure_check and
**My exposure log shows checks for less than 14 days**
https://www.coronawarn.app/de/faq/#exposure_check
**In den Begegnungsüberprüfungen sind die Aufzeichnungen von weniger als 14 Tagen gespeichert**
to resolve the issue described in https://github.com/corona-warn-app/cwa-website/issues/891.
Google changed the UI and has pushed the exposure checks one level deeper, so that it is now necessary to tap the three-dot overflow menu in order to access exposure checks. The three-dot overflow menu is referred to in the FAQ as "three-dot icon" for better general understanding.
changes are marked up in yellow.
> Add three-dot icon for access to Google exposure checks (closes #891)

- src/data/faq.json
- src/data/faq_de.json
Some FAQ entries were missing labels (e.g. `[Apple/iOS]`). So, I've added them.
> [Minor] Add missing labels to some FAQ entries

- src/data/faq.json
- src/data/faq_de.json
This PR fixes minor typographical errors in the website files faq.json and faq_de.json.
**EN**
deceides => decides 
continously => continuously
Exosure => Exposure
**DE**
Poblemen => Problemen 
heisst => heißt 
Poisitivkennung => Positivkennung
> Minor typographical errors in faq files (EN & DE) fixed

- blog/2020-08-25-notes-qr-codes/index.md
- blog/2020-08-25-notes-qr-codes/index_de.md
This PR corrects a linking error described in issue #986.
**QR Code scanned but no test result in the Corona-Warn-App**
https://www.coronawarn.app/en/blog/2020-08-25-notes-qr-codes/
and
**QR-Code gescannt aber kein Testergebnis in der Corona-Warn-App**
https://www.coronawarn.app/de/blog/2020-08-25-notes-qr-codes/
now link to the correct FAQ article.
**EN**
https://www.coronawarn.app/en/blog/2020-08-25-notes-qr-codes/ 
"In some cases, [error messages](https://www.coronawarn.app/en/faq/#qr_test) ..."
links now to [#qr_scan](https://www.coronawarn.app/en/faq/#qr_scan).
**DE**
https://www.coronawarn.app/de/blog/2020-08-25-notes-qr-codes/ 
"In some cases, [error messages](https://www.coronawarn.app/de/faq/#qr_test) ..."
links now to [#qr_scan](https://www.coronawarn.app/de/faq/#qr_scan).
> Correct blog link to scan error FAQ (closes #986)

- gulpfile.js
This commit updates the app versions from 1.15.1 -> 1.15.2.
See iOS release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.15.2
See Android release: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.15.2
> Update iOS & Android app versions

- src/data/faq.json
- src/data/faq_de.json
This PR adds a mention of the blog post https://www.coronawarn.app/de/blog/2021-03-31-corona-warn-app-test-integration/ to the FAQ entry "#rapid_test".
<details>
<summary>Screenshots of the changes</summary>
</details>
--- 
Closes #1040
> Mention blog post from `#rapid_test` entry (Closes #1040)

- src/data/download.json
- src/data/download_de.json
This PR improves the wording of the [download page](https://www.coronawarn.app/?target=download).
Waiting on feedback from @svengabr, @heinezen or @dsarkar.
> Improve & correct download page

- blog/2021-04-23-qr-code-generator-website/index.md
- src/data/eventregistration_de.json
This PR fixes some typos discovered by @DerVogel2020 in https://github.com/corona-warn-app/cwa-website/pull/1132#pullrequestreview-643532898.
This PR also changes "Corona warning app" to "Corona-Warn-App" in the English blog post "2021-04-23-qr-code-generator-website".
> Fix typos in `eventregistration` & blog post

- src/data/eventregistration.json
This tiny PR aligns the example for the description to the German one (changed through #1134).
**Changed:**
"Shopping center" -> "Hairdresser"
> Align English to German (QR-Code generator)

- src/data/eventregistration.json
- src/data/eventregistration_de.json
https://www.coronawarn.app/en/eventregistration/
The Place field is called Address. This is inconsistent with the mobile app, where the field is called Place.
In German, the same applies. Additionally, the label is "Beschreibung", not "Bezeichnung" like in the app.
A user was [confused](https://social.tchncs.de/@erAck/106126160685373319) why an Address was required on the website.
> Make labels in QR code generator consistent with app

- gulpfile.js
This PR bumps the Android app version from 2.0.4 to 2.0.5.
Android release: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.0.5
> Bump Android app version

- src/data/eventregistration.json
- src/data/eventregistration_de.json
This PR removes the option to choose "Other" in the QR-Code generator since there is no option for this in the app and thus the app shows an error/unlocalized string.
Related: https://github.com/corona-warn-app/cwa-app-ios/issues/2564
> Remove "other" from QR-Code generator

- blog/2021-05-02-cwa-2-1-schnelltests/index.md
This PR corrects some typos in the English language announcement of CWA 2.1 on https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/
1. "A positive test **results**" => "A positive test result", since "A" specifies singular, then "result" must agree.
2. "...the Corona-Warn-App doesn’t **safe** personal data in accordance the decentralized approach." => "...the Corona-Warn-App doesn’t save personal data in accordance with the decentralized approach."
-- See https://dictionary.cambridge.org/dictionary/english/save (meaning A2) not https://dictionary.cambridge.org/dictionary/english/safe
-- See https://dictionary.cambridge.org/dictionary/english/accordance (in accordance with)
3. "In case of a positive PCR test, users should share this test result, too." removed comma …
> Correct blog typos in 2.1 announcement EN

- src/assets/js/eventregistration.js
- src/partials/page-eventregistration.html
This PR resolves #1144 and also resolves #1136. 
With this PR the download button is initially disabled when accessing the page. The disabled attribute is removed when the "create" button is clicked. 
Also I removed the logic which creates a new qr code when clicking the download button. To make it more clear that the download button only downloads the current banner I've repositioned the button under the banner.
> Improve eventregistration download button behavior 

- THIRD-PARTY-NOTICES
- package-lock.json
- package.json
- src/assets/js/eventregistration.js
- src/assets/scss/vendor/_eventregistration.scss
- src/data/eventregistration.json
- src/data/eventregistration_de.json
- src/partials/page-eventregistration.html
This PR adds cleave.js to the date and time fields which forces users to use the given date pattern and adds separators automatically which resolves #1143. 
Also the input field defaultcheckinlength got replaced by two select fields for hours and minutes. This resolves #1192 because with the select fields it is not possible anymore to select more than 3600 minutes. In addition this resolves #1155 because the number input field got replaced by select fields.
> Event date time pickers and select fields for defaultcheckinlength

- src/data/faq.json
- src/data/faq_de.json
This PR removes "International phone numbers" from the title of the FAQ entry "internation_phone_numbers", since we also store the national phone numbers there.
Also, a "." was moved out of a link in "who_can_help". Instead, the "." is now normal text (;
> Remove "International phone numbers" from the title of "international_phone_numbers"

- src/data/faq.json
The FAQ aligns capitalization of the English language FAQ section title "Rapid antigen test" with all other section titles by changing it to "Rapid Antigen Test", since all other section titles are already capitalized.
> FAQ: Capitalize Rapid Antigen Test section title

- src/data/screenshots_de.json
This PR changes"Check-In" to "Check-in" in the German screenshot page to be consistent with the app.
> German Screenshots page: "Check-In" -> "Check-in"

- src/data/faq.json
- src/data/faq_de.json
This PR adds the information to the FAQ entries
https://www.coronawarn.app/en/faq/#incompatibility_warning and
https://www.coronawarn.app/de/faq/#incompatibility_warning 
that the Bluetooth Low Energy compatibility checks were introduced with version 2.2 of CWA. The PR addresses issue https://github.com/corona-warn-app/cwa-website/issues/1274.
Without this information users may think that there is a bug in the app if they had previous versions of the app installed, have updated and are seeing a warning message for the first time.
Incidentally also one typo in the EN version of the FAQ entry is corrected at the same time.
> Add introduction version info for BLE compatibility check (closes #1274)

- cypress/integration/hotline_spec.js
This PR fixes the failing cypress test [hotline_spec.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/hotline_spec.js) mentioned in issue #1282.
The test was broken by changes to [global.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/global.json) in PR https://github.com/corona-warn-app/cwa-website/pull/757 which removed the "+49" prefix from the "Hotline App" and the "Hotline TAN" phone numbers.
```
npm run test:prepare
npn run test
```
produces output including the following:
```
Running:  hotline_spec.js                                                                 (3 of 3)
Test Hotline phone number
√ Verify App and TAN Hotline (778ms)
1 passing (832ms)
```
> Update hotline telephone numbers in cypress test

- README.md
This PR corrects a link in [README.md](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) to show the count of all open issues in the repository, not just the ones with a question label attached to them. The issue was raised in #1285.
> Correct badge to show all issue count (closes #1285)

- src/partials/page-eventregistration.html
Added bootstrap's missing form-select class to select inputs so
that they display the down-pointing arrow.
> Event QR-Code: add form-select class to select inputs

- src/data/index_de.json
This tiny PR aligns the title on the German main page to the title on the English main page.
What it does:
"Open-Source-Projekt für Corona-Warn-App" -> "Corona-Warn-App Open-Source-Projekt"
> Align German text on main page to English

- src/data/faq.json
- src/data/faq_de.json
This PR explains that the implementation is different under iOS in `#rat_how_long_valid`.
<details>
<summary>Preview of the changes</summary>
| English | German |
|---|---|
|<img width="1033" alt="Bildschirmfoto 2021-06-05 um 23 23 22" src="https://user-images.githubusercontent.com/67682506/120905858-4cec3380-c655-11eb-9afd-abf1ab267d42.png">|<img width="1033" alt="Bildschirmfoto 2021-06-05 um 23 22 45" src="https://user-images.githubusercontent.com/67682506/120905856-4b227000-c655-11eb-8867-20c74c232049.png">|
</details>
---
**Closes #1330**
> Mention different implementation under iOS in `#rat_how_long_valid` (Closes #1330)

- src/pages/de/blog/archiv/index.html
- src/pages/de/blog/index.html
- src/pages/de/community/index.html
- src/pages/de/eventregistration/index.html
- src/pages/de/faq/index.html
- src/pages/de/imprint/index.html
- src/pages/de/index.html
- src/pages/de/news/index.html
- src/pages/de/privacy/index.html
- src/pages/de/terms-of-use/index.html
- src/pages/en/blog/archive/index.html
- src/pages/en/blog/index.html
- src/pages/en/community/index.html
- src/pages/en/faq/index.html
- src/pages/en/imprint/index.html
- src/pages/en/index.html
- src/pages/en/news/index.html
- src/pages/en/privacy/index.html
- src/pages/en/screenshots-archive/2-2.html
- src/pages/en/screenshots/index.html
- src/pages/en/terms-of-use/index.html
- src/pages/index.html
---
This PR introduces #1331. It aligns the `page-title`s on most of the pages and improves their descriptions (`page-description`).
Closes #1331 
---
¹ This is needed because #1329 adds a new site and I wanted to edit this too, so I used `svengabr/screenshot-archive` as the starting branch.
My change is in: https://github.com/corona-warn-app/cwa-website/pull/1332/commits/df977e7028d2b7368989de368510bb5a7294efa5
> Align all `page-title`s & improve `page-description` s (Closes #1331)

- src/services/blog-processor.js
This PR fixes what has been described in #1201.
I tried to do it like this: `{{#if lang_de}}am{{else}}on{{/if}}` but this only worked on a individual blog post but not on https://www.coronawarn.app/en/blog/ for some reason, so the simplest solution I saw was to replace "on" with a ",", which works in both languages.
> Replace "on" with "," (Fixes #1201)

- README.md
- gulpfile.js
- package.json
This adds a new option `--skip-compression` to the gulpfile which results in a skip over the webp compression for images on the website. It can also be used via npm:
```
npm run start-fast
```
Useful if you want to just look at the website (or specifically the FAQ) without having to wait for the compression to finish.
> Add gulp option to skip image compression

- src/data/faq.json
- src/data/faq_de.json
This PR fixes the vaccination certificate section from showing as active section when you open the FAQ page.
> Fix showing vaccination certificate section as active although it isn't

- src/data/faq.json
- src/data/faq_de.json
Fixes https://github.com/corona-warn-app/cwa-website/issues/1343
Warum bekomme ich die Fehlermeldung „Dieser QR-Code ist kein gültiges Impfzertifikat (VC_PREFIX_INVALID)“, wenn ich versuche meinen Impf-QR-Code zu scannen?
---
 
Es gibt derzeit (Stand: 9 Juni 2021) noch keine Impfzertifikate mit QR-Codes, die mit der App eingescannt werden können.
 
Das in der Vergangenheit und momentan ausgestellte Dokument ist trotz des QR-Codes kein gültiges digitales Impfzertifikat, sondern lediglich eine Impfbescheinigung, die dem deutschen Infektionsschutzgesetz folgt, nicht aber den aktuellen neuen abgestimmten europäischen Richtlinien für ein digitales Impfzertifikat.
 
Diese neuen digitalen Impfzertifikate werden demnächst ausgestellt. Solche digitalen Zertifikate können nur von autorisierten …
> Add FAQ entry reg. „VC_PREFIX_INVALID“ error

- gulpfile.js
This PR bumps the current iOS app version from 2.3.2 to 2.3.3.￼￼
Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.3.3
> Bump iOS app version

- blog/2021-06-24 CWA 2.4 Testzertifikat/index.md
This PR corrects the typo "varify" and changes it to "verify" in the 2.4 blog announcement.
The page https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4/ is corrected.
> Fix typo "varify" in 2.4 blog

- blog/2021-06-24 CWA 2.4 Testzertifikat/index_de.md
This PR fixes a typo in the german blog entry https://www.coronawarn.app/de/blog/2021-06-24-cwa-version-2-4/
replace Starbildschirm with Startbildschirm
> Fix typo "Starbildschirm" in 2.4 blog

- gulpfile.js
This PR bumps the current app versions from 2.4 to 2.4.1.
iOS release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.4.1
Android release: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.4.1
> Bump current app versions

- src/data/faq_de.json
This PR corrects an issue from PR https://github.com/corona-warn-app/cwa-website/pull/1435 which added `&nbsp;` into German abbreviations.
I noticed that this doesn't work in titles of the https://www.coronawarn.app/de/faq/ sourced from [faq_de.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq_de.json). Unfortunately I missed one occurrence of this during testing. Sorry about that!
If anybody happens to know how to add a `&nbsp;` into a `"title":`  I would be happy to know. I guess this is being processed by `gulp`.
---
I also corrected an unrelated typo in https://www.coronawarn.app/de/faq/#rat_same_in_cwa, changing
"Scnelltest-QR-Code" to "Schnelltest-QR-Code".
> Remove nbsp from FAQ title

- src/data/faq.json
- src/data/faq_de.json
This PR fixes two issues in
https://www.coronawarn.app/en/faq/#hc_prefix_invalid and
https://www.coronawarn.app/de/faq/#hc_prefix_invalid
(see https://github.com/corona-warn-app/cwa-website/issues/1462#issuecomment-878303906).
1) In the text of https://www.coronawarn.app/en/faq/#hc_prefix_invalid it says:
"Why do I get the error message 'This QR code is not a valid certificate. (HC_PREFIX_INVALID)' when I try to scan my vaccination QR code?"
The word "vaccination" is removed, since the error can refer to vaccination, test or recovery certificates.
2) The URL https://www.coronawarn.app/en/faq/#hc_prefix_invalid does not work correctly, although it does manage to show the article by falling back to search.
The URL https://www.coronawarn.app/de/faq/#hc_prefix_invalid does not work correctly. …
> Make hc_prefix_invalid bookmarks work

- src/data/faq_de.json
This PR fixes a gramma issue in the FAQ entry `#hc_prefix_invalid`.
> Fix double "kann" in FAQ entry `#hc_prefix_invalid`

- src/data/faq.json
- src/data/faq_de.json
This PR reflects the change in CWA 2.5 that certificates for different people can be stored, therefore it can no longer be assumed that a scan failure is for "my certificate". Instead it is now referred to a "a certificate".
The title of 
https://www.coronawarn.app/en/faq/#vac_cert_invalid
is now
"Why do I get the error message 'This QR code is not a valid vaccination certificate. (VC_PREFIX_INVALID)' when I try to scan a vaccination QR code?"
and for
https://www.coronawarn.app/de/faq/#vac_cert_invalid
the title is now
"Warum bekomme ich die Fehlermeldung 'Dieser QR-Code ist kein gültiges Impfzertifikat (VC_PREFIX_INVALID)', wenn ich versuche einen Impf-QR-Code zu scannen?"
The PR is one of several to follow which will address issue …
> FAQ: vac_cert_invalid not necessarily my certificate

- src/data/faq.json
- src/data/faq_de.json
This PR updates
https://www.coronawarn.app/en/faq/#vac_cert_what and
https://www.coronawarn.app/de/faq/#vac_cert_what
to cover the enhancement in CWA 2.5 that digital certificates for multiple people can be stored in the app. The wording of the article is changed accordingly.
It is one of the PRs to resolve issue https://github.com/corona-warn-app/cwa-website/issues/1409.
> FAQ: Update vac_cert_what for multiple certificates

- src/data/faq.json
This PR corrects three typos in https://www.coronawarn.app/en/faq/#vac_cert.
> FAQ: Correct typos in vac_cert (en)

- gulpfile.js
This commit bumps the current iOS version form 14.6 to 14.7.
Apple Release: https://developer.apple.com/news/releases/?id=07192021c
> Bump current iOS version

- src/data/faq.json
- src/data/faq_de.json
This PR changes the title of
https://www.coronawarn.app/en/faq/#hc_prefix_invalid and
https://www.coronawarn.app/de/faq/#hc_prefix_invalid
to refer to "a QR code" instead of "my QR code" / "einen QR-Code" instead of "meinen QR-Code", since the QR code can be from any person. The app is not restricted to only scanning QR codes from one person any more.
In the English text I also tidied up some whitespace placement.
> FAQ: Make hc_prefix_invalid title impersonal

- src/data/faq_de.json
This PR corrects two typos in titles in the section
https://www.coronawarn.app/de/faq/#test_cert "Testzertifikat".
In https://www.coronawarn.app/de/faq/#test_cert_why
"Wozu dient das digitales COVID-Testzertifikat?" is corrected to read
"Wozu dient das digitale COVID-Testzertifikat?".
In https://www.coronawarn.app/de/faq/#test_cert_rat_and_pcr
"Kann ich Testzertifikate für Schnelltests und PCR-Test anfordern?" is corrected to read
"Kann ich Testzertifikate für Schnelltests und PCR-Tests anfordern?".
> Correct typos in #test_cert

- src/data/faq.json
- src/data/faq_de.json
This PR follows on from the issue https://github.com/corona-warn-app/cwa-website/issues/1238 suggesting that FAQ articles need to be reviewed so that they clearly differentiate between PCR tests and Rapid Antigen Tests (RAT). Many articles were written before  RATs were introduced.
For the FAQ articles 
https://www.coronawarn.app/en/faq/#international_phone_numbers "How to reach us" and
https://www.coronawarn.app/de/faq/#international_phone_numbers "So erreichen Sie uns"
the qualifier "PCR" is added to the term test result / Testergebnis.
Only positive results from PCR tests (not from Rapid Antigen Tests) qualify for a TAN.
The app is clear about this and shows the following text:
> TAN hotline only for PCR tests

- src/data/faq.json
- src/data/faq_de.json
This PR resolves https://github.com/corona-warn-app/cwa-website/issues/1560 by aligning the list of countries providing Business Rules for EU Digital COVID Certificate validation with the blog entry.
https://www.coronawarn.app/en/faq/#cert_eu_travel and
https://www.coronawarn.app/de/faq/#cert_eu_travel
are changed to:
1. Remove Austria / Österreich from the list
2. Add Ireland / Irland to the list
3. Add Slovenia / Slowenien to the list
4. Separate Germany / Deutschland
5. List countries alphabetically
The FAQ entries now agree with the countries listed in 
https://www.coronawarn.app/en/blog/2021-07-28-cwa-version-2-6/ 
(Germany, Spain, the Netherlands, Ireland, Luxembourg, Slovenia and Lithuania)
and
https://www.coronawarn.app/de/blog/2021-07-28-cwa-version-2-6/
(Deutschland, Spanien, …
> Correct list of Business Rules countries (fixes #1560)

- blog/2021-08-05-explain-statistics-tiles/index_de.md
This PR corrects the issue reported in https://github.com/corona-warn-app/cwa-website/issues/1581 "Language switch for Blog - Statistic tiles - fails".
In https://github.com/corona-warn-app/cwa-website/blob/master/blog/2021-08-05-explain-statistics-tiles/index_de.md
`page-name: statistikkacheln`
is changed to
`page-name: statistictiles`
to be identical to the value of
`page-name:`
in https://github.com/corona-warn-app/cwa-website/blob/master/blog/2021-08-05-explain-statistics-tiles/index.md
1. Open https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/
2. Click on "DE" in header
3. Check that page https://www.coronawarn.app/de/blog/2021-08-05-statistictiles/ is displayed without error 404
4. Click on "EN" in header
5. Check that page …
> Fix index_de.md for statisticstiles (closes #1581)

- blog/2021-08-05-explain-statistics-tiles/index.md
This PR corrects typos and inconsistent rendering of terms in 
https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/
consistent rendition of:
- 7-Day Incidence (as displayed in app)
- 7-Day R Value (as displayed in app)
- Corona-Warn-App (as named in app stores)
- COVID-19 (as generally used by RKI - see https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/nCoV.html)
- Robert Koch Institute (English name without hyphen as per https://www.rki.de/EN/Service/Imprint/imprint_node.html)
and a couple of typos.
> Fix term consistency and typos in statistic tiles blog (EN)

- blog/2021-08-05-explain-statistics-tiles/index_de.md
This PR removes a line break from the blog post https://www.coronawarn.app/de/blog/2021-08-05-statistictiles/.
> `2021-08-05-statistictiles` blog: Remove line break too much (DE)

- src/data/faq.json
- src/data/faq_de.json
This PR supports the resolution of https://github.com/corona-warn-app/cwa-website/issues/1238 "FAQ: Differentiate between PCR Test and Rapid Antigen Test".
It modifies the FAQ articles:
- https://www.coronawarn.app/en/faq/#red_card_how_to_test "Red Card? How to go through Corona testing" and
- https://www.coronawarn.app/de/faq/#red_card_how_to_test "Rote Karte? So geht es zum Corona Test"
The type of test is explicitly named as PCR test.
---
In the "See also" section of the FAQ articles links are added to:
EN
[If I see a high-risk encounter in the App, i.e. a red card, should I do a rapid antigen test or PCR-Test?](http://localhost:8000/en/faq/#rat_red_card_which_test) and
[How to behave if I am partially or completely vaccinated, but receive a red warning in the …
> FAQ: red_card_how_to_test made explicit for PCR test

- src/data/faq.json
- src/data/faq_de.json
This PR resolves https://github.com/corona-warn-app/cwa-website/issues/1597 "Outdated news article for Google ENS security vulnerability".
- The articles are moved from "News" to "Resolved"
- The titles are updated to use the [Google/Android] prefix
- Since the event is now more than 3 months old, the past tense is used
- The information about 98% rollout (which will no longer be correct) has been replaced with a statement that a fix has been rolled out
Users can determine that their current version of the Google Play services / Google Play-Dienst app is higher or equal to version 21.15 via Android > Settings > Apps. This is not stated in the FAQ, since it is a standard Android function and any smartphone which is connected to Internet will automatically update to the latest Google Play …
> FAQ: Move google_security_vulnerability to Resolved

- src/data/faq.json
- src/data/faq_de.json
This PR adds a reference to the science blog to the FAQ entry "data_donation_and_EDUS".
<details>
<summary>Preview of the changes</summary>
| English | German |
|---|---|
|<img width="1030" alt="EN" src="https://user-images.githubusercontent.com/67682506/129010901-83b3a98e-b305-436f-95b3-64157b6b485d.png">| <img width="1030" alt="DE" src="https://user-images.githubusercontent.com/67682506/129010887-6c1736f0-3dc2-4aba-83de-07a312c0ed6f.png">|
</details>
---
**Closes #1605**
> Add a reference to the science blog (Closes #1605)

- src/data/faq.json
- src/data/faq_de.json
- src/data/global.json
This PR updates the "Where can I get tested" links which are on the top of every page. The images in the FAQ entry "where_can_i_get_tested" are updated too. There are no big visible differences, so no screenshots this time (;
--- 
**Closes #1611**
---
Internal Tracking ID: [EXPOSUREAPP-8937](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8937)
> Update "Where can I get tested" link (Addresses #1611)

- src/data/faq_de.json
- src/partials/page-faq.html
As a response to [this issue](https://github.com/corona-warn-app/cwa-website/issues/1540), here's the pull request to reposition the glossary. The glossary will be displayed at the bottom of the page instead of on top, but there's still a hyperlink below the search bar that will lead to the glossary, so you don't have to scroll all the way down. 
Comparison of the top of the new FAQ page and the old FAQ page:
> Repositioning of the glossary

- src/data/screenshots-archive-2-2.json
- src/data/screenshots-archive-2-3.json
- src/data/screenshots-archive-2-4.json
- src/data/screenshots-archive-2-5.json
- src/data/screenshots-archive-2-6.json
- src/data/screenshots-archive.json
- src/data/screenshots.json
Resolves partially #1653
Ideally as mentioned in #1653 the GitHub workflow would be adjusted to detect such incorrect anchors.
> Fix `ios_rat` anchors being used for Android screenshots

- src/data/faq.json
- src/data/faq_de.json
As a response to [this issue](https://github.com/corona-warn-app/cwa-website/issues/1678), here's the pull request to replace cross-references with links to their respective entry. See the images below for an example.
Old:
New:
> Replacement of cross-references with links to the respective entry

- src/data/eventregistration_de.json
This commit makes the button text "csvFile" more clear.
Currently the text says "CSV Datei laden", the user could think that the button downloads the file ("laden") instead of giving the user the chance to upload a file.
<details>
<summary>Preview of the change (DE only)</summary>
</details>
> Make the text "CSV Datei laden" more clear

- src/data/screenshots.json
- src/data/screenshots_de.json
This PR addresses issue https://github.com/corona-warn-app/cwa-website/issues/1710 for 
- https://www.coronawarn.app/en/screenshots/#android_invalid_certificate
- https://www.coronawarn.app/de/screenshots/#android_invalid_certificate
The links in the above sections are changed to use screenshots of invalid certificates from iOS for Android (since are no equivalent Android screenshots available).
Previously 2 of the 3 screenshots in the Android sections were incorrectly valid where they were supposed to demonstrate what an invalid screenshot looked like.
Now section 
https://www.coronawarn.app/en/screenshots/#android_invalid_certificate
is identical to
https://www.coronawarn.app/en/screenshots/#ios_invalid_certificate
and
https://www.coronawarn.app/de/screenshots/#android_invalid_certificat …
> Fix/8884 invalid certificates Android 2.8

- gulpfile.js
This PR bumps the current iOS app version from 2.9.0 to 2.9.1.
---
GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.9.1
> Bump current iOS app version

- src/data/faq.json
- src/data/faq_de.json
As a response to these issues ([Create FAQ eu_dcc_booster #1735](https://github.com/corona-warn-app/cwa-website/issues/1735), [Create FAQ eu_dcc_export #1645](https://github.com/corona-warn-app/cwa-website/issues/1645)), here's the pull request to add both faq entries for the upcoming release 2.10. While creating the index for eu_dcc_booster, I've stumbled upon missing index links in test certificate faq entries, and have added them in this commit too. Times mentioned in vac_cert_booster_cwa have also been adjusted.
eu_dcc_export: 
DE:
EN:
vac_cert_booster (used to be named eu_dcc_booster):
DE:
EN:
vac_cert_booster_cwa:
DE:
EN:
---
Internal Tracking ID: [EXPOSUREAPP-](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-)
Internal Tracking ID: …
> Add eu_dcc_export + vac_cert_booster

- src/data/screenshots.json
This PR sets the screenshot headings for the current CWA version 2.9 in English and for iOS and Android consistently to title case. It resolves issue #1740.
It does **not** change any archived screenshot versions.
> Capitalize English screenshot headings (closes #1740)

- cypress/integration/check_links.js
This PR corrects an error in the cypress script https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/check_links.js, introduced by PR https://github.com/corona-warn-app/cwa-website/pull/1794, where in 
https://github.com/corona-warn-app/cwa-website/blob/a56849a712d91d3eed500b62c480614d0f57d6ec/cypress/integration/check_links.js#L16
the directory  `/de/blog/archive/` is listed for link checking.
There is however no https://www.coronawarn.app/en/blog/archive/ so it returns a 404 and fails this test.
The correct German-language directory is https://www.coronawarn.app/en/blog/archiv (without an "e" at the end).
The cypress script is corrected to `/de/blog/archiv/` so that it is able to check an existing directory.
(Note this is the only directory where the …
> Correct link to de blog archiv in link checker

- science/2021-06-15-science-blog-1/index.md
- science/2021-06-15-science-blog-1/index_de.md
Removed <a href> from videos on science blog 1 as they are not needed, point nowhere and create dead links.
> Removed Deadlinks from Science Blog 1

- blog/2021-06-24 CWA 2.4 Testzertifikat/index.md
This PR resolves an issue https://github.com/corona-warn-app/cwa-website/issues/1803 in the English-language blog article https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4/ announcing the release of version 2.4 where there is a missing graphic.
The German-language blog article https://www.coronawarn.app/de/blog/2021-06-24-cwa-version-2-4/ includes the screenshot https://www.coronawarn.app/assets/img/blog/2021-06-24%20CWA%202.4%20Testzertifikat/teststelle-nicht-unterstützt.png which is not available as a screenshot from an English device.
The 2.4 English article is understandable even without presenting such a screenshot. The PR removes the unsightly failed link from the source. This also remediates the issue that the bad link is reported in web link checkers.
The text now …
> Remove link to missing test station status graphic in 2.4 blog announcement (resolves #1803)

- gulpfile.js
This PR bumps the current Android app version from 2.11.1 to 2.11.2.
---
GitHub release: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.11.2
> Bump current Android app version

- src/data/faq.json
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/1861 "Inconsistent spelling "traveling" / "travelling" in FAQs" by changing occurrences of "travelling" in https://www.coronawarn.app/en/faq/ to be spelled as "traveling".
It makes the FAQ consistent within itself, also concerning the related word "traveler". It aligns the FAQ with text messages from the (Android) app which also use the spelling "traveling".
> Use spelling "traveling" in FAQs (fixes #1861)

- docs/WRITE_BLOG_POSTS.md
This PR adds advice to the document [docs/WRITE_BLOG_POSTS.md](https://github.com/corona-warn-app/cwa-website/blob/master/docs/WRITE_BLOG_POSTS.md) in support of resolving the issue https://github.com/corona-warn-app/cwa-website/issues/1819 "Inconsistent use of absolute and relative paths to https://www.coronawarn.app".
The added text is:
> Additional linking hints for WRITE_BLOG_POSTS

- blog/2021-10-11-wichtigste-Funktionen/index.md
This PR corrects a typo of text used in the meta-data of
https://www.coronawarn.app/en/blog/2021-10-11-cwa-most-important-features/
It removes the extra character "W" from 
`page-description: "WWhy the Corona-Warn-App is important right now"` in
https://github.com/corona-warn-app/cwa-website/blob/master/blog/2021-10-11-wichtigste-Funktionen/index.md
Search engines may use this meta-data so it should be corrected.
> Typo in page description of "Why the Corona-Warn-App is important right now"

- src/data/faq.json
- src/data/faq_de.json
This PR coverts the following FAQ Glossary entries to use relative paths in hyperlinks:
- https://www.coronawarn.app/en/faq/#glossary_data_donation "Data Donation"
- https://www.coronawarn.app/de/faq/#glossary_data_donation "Datenspende"
- https://www.coronawarn.app/en/faq/#glossary_ene "Exposure Notification Express (ENE)"
- https://www.coronawarn.app/de/faq/#glossary_ene "Exposure Notification Express (ENE)"
It follows from the issue #1819.
This should be the last PR at the moment to covert absolute paths to relative paths.
> Convert Glossary entries to use relative paths

- blog/2021-10-19-cwa-2-12/index.md
- blog/2021-10-19-cwa-2-12/index_de.md
This PR converts the link to the [2.11 blog article](https://www.coronawarn.app/en/blog/2021-10-06-cwa-version-2-11/) in the [2.12 blog article](https://www.coronawarn.app/en/blog/2021-10-19-cwa-version-2-12/) to use a relative path instead of an absolute path.
It aligns the blog article with the newly-added recommendations in [WRITE_BLOG_POSTS.md#link-to-other-locations](https://github.com/corona-warn-app/cwa-website/blob/master/docs/WRITE_BLOG_POSTS.md#link-to-other-locations)
**EN**
`https://www.coronawarn.app/en/blog/2021-10-06-cwa-version-2-11/` is changed to
`/en/blog/2021-10-06-cwa-version-2-11/`
**DE**
`https://www.coronawarn.app/de/blog/2021-10-06-cwa-version-2-11/` is changed to
`/de/blog/2021-10-06-cwa-version-2-11/`
This follows from the publication PR …
> Convert 2.12 blog to use relative path

- cypress/integration/check_anchor_links.js
Due to issue #1986 I had added two more conditions to search for a container ID. Now the anchor must be different from 'top' and also apart from have a '#', the part behind '#' have to contains content. Let's see some examples:
Our test will check for:
- page.com/url#tag
Our test will avoid:
- page.com/url#top
- page.com/url#
Because it is very common to use this tag to go to the top of the page without the necessity of exist a container with a 'top' ID
- The test will works for everyone without errors
- If an editor forgot to include content behind '#' the test will not detect it or can be confused by use '#' to go to the top of the page
> Fix anchor link Cypress test

- blog/2021-11-04-booster-notifications/index.md
This PR corrects some typos in:
https://www.coronawarn.app/en/blog/2021-11-04-cwa-booster-notification/
"Corona-Warn-App notifies users about a booster vaccination"
I mentioned about this in https://github.com/corona-warn-app/cwa-website/pull/2009#issuecomment-960546952. Since I didn't receive any feedback so far, I have put them into this PR, so they can be corrected easily.
I have not removed the `jsessionid` which I mentioned in https://github.com/corona-warn-app/cwa-website/issues/2013. It should not be there, but I didn't want to confuse things by removing it in parallel to the open issue.
> Fix typos in booster notifications blog (EN)

- src/data/faq.json
- src/data/faq_de.json
- src/data/faq_redirects.json
This PR changes the anchor "vac_cert_invalid_211111" to "vac_cert_invalid_211115", as the date was changed from 11.11.20212 to 15.11.2021.
I also added a FAQ redirect and confirmed that this works in German and English locally.
> Change anchor "vac_cert_invalid_211111" to "vac_cert_invalid_211115" & add FAQ redirect

- src/data/faq.json
- src/data/faq_de.json
This PR removes a "." from the `vac_cert_booster` FAQ title to be consistent with other FAQ entry titles, e.g. the [Questions and answers about the event registration](https://www.coronawarn.app/en/faq/#check_in_index) entry.
> Remove "." from `vac_cert_booster` FAQ title to be consistent with other FAQ entry titles

- src/assets/scss/_analyse.scss
Due to issue #2028 I changed the z-index of the board titles so they dont appear on top of the main menu
> Fixed the z-index of the board title in analyse

- blog/2021-11-04-booster-notifications/index.md
This PR addresses the second point in issue https://github.com/corona-warn-app/cwa-website/issues/2013:
On blog page https://www.coronawarn.app/en/blog/2021-11-04-cwa-booster-notification/ "Corona-Warn-App notifies users about a booster vaccination":
2. The link https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html;jsessionid=75D575152D0A98168E5703E0D653EEE4.internet112 contains a jsessionid which should normally be removed before using as a hyperlink from the blog page.
The link on this blog page is simplified by this PR to https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html by removing `;jsessionid=75D575152D0A98168E5703E0D653EEE4.internet112`
Reference:
https://en.wikipedia.org/wiki/Session_ID
> Remove jsessionid in booster blog (EN)

- blog/2021-10-04-dashboard/index_de.md
@dsarkar 
As requested: 🙂 
This PR corrects a typo in https://www.coronawarn.app/de/blog/2021-10-04-key-figures-dashboard/ "Kennzahlen-Dashboard zur Corona-Warn-App"
The sentence:
"Warnungen mit grünem und rotem Risiko: Daten aus der Privacy Preserving Analytics, PPA)."
is corrected to
"Warnungen mit grünem und rotem Risiko: Daten aus der Privacy Preserving Analytics (PPA)."
This follows on from https://github.com/corona-warn-app/cwa-website/pull/2038#issuecomment-965207757.
> Correct typo in Oct 4 2021 blog (DE) - PPA

- blog/2021-11-15-cwa-recalled-certificates/index.md
- blog/2021-11-15-cwa-recalled-certificates/index_de.md
@dsarkar 
This PR is for:
EN https://www.coronawarn.app/en/blog/2021-11-15-cwa-recalled-vaccination-certificates/ "Corona-Warn-App informs users about recalled vaccination certificates"
- grammar: users => users' (possessive) 
- at pharmacy = at a pharmacy
- booklet an ID => booklet and ID
- Highlight text to update in last line, like in the German version.
---
DE https://www.coronawarn.app/de/blog/2021-11-15-cwa-recalled-vaccination-certificates/ "Corona-Warn-App informiert Nutzer*innen über zurückgerufene Impfzertifikate"
- escape asterisks "*" => "`\*`", otherwise the text is interpreted as italics
- ein zurückgerufenen Zertifikat => ein zurückgerufenes Zertifikat
- Added operating system next to version numbers in last line, like in the English version.
> Fix typos and formatting for blog recalled certificates

- src/assets/scss/_analyse.scss
- src/data/analyse_de.json
Reduced the font size of the Further dashboards links in the analysis section so they all show up in one line and added (DE/EN) at the end of the links in the german version
> Fixed link styles and link names

- src/data/faq.json
This PR adds a missing "?" to the title of `eu_dcc_validity`.
"How long is my certificate valid​" is changed to
"How long is my certificate valid​?".
> Add question mark to eu_dcc_validity EN title

- src/assets/js/app.js
We discovered that the issue #2114  was caused because of the event listener that we added in pr #2053. We added a new function so that the event listener only works in desktop devices.
> Fixed scroll in IOS devices

- src/partials/header.html
This PR removes the underline on header pages of https://www.coronawarn.app such as on https://www.coronawarn.app/en/faq/ between "Where to get tested?" and "Missing test result/test certificate?". This resolves the issue #2122.
After applying the fix the header shows as follows, with no underline underneath the spaces:
---
EN
---
DE
> Remove underline from header whitespace (resolves #2122)

- src/assets/js/analyse/modal.js
- src/assets/scss/_analyse.scss
- src/data/analyse_de.json
- src/data/analyse_en.json
- src/partials/page-analyse.html
In this PR, I have shortened the text block under the title on Analysis page. The second part of the text block had been inserted on a modal message, looking like: 
**English**
**German**
> Shorted text block under Analysis page title

- cypress/integration/check_links.js
In this PR, I had solved an issue that occurred to me making tests for other task. The text show on softExpects in entries code block had bad references to vars used on the previous code block. The test functionality was correct, but the text shown not.
> Fix reference on show test result

- src/data/faq.json
- src/data/faq_de.json
This PR moves the FAQ article:
- https://www.coronawarn.app/en/faq/#where_to_get "Where can I get the app?"
- https://www.coronawarn.app/de/faq/#where_to_get "Wo bekomme ich die App?"
from the end of the Availability section to the beginning of this section where it is easier to find. The `#where_to_get` article is the top-level piece of information regarding availability and it deserves a place at the top of the section with the other details below it.
The Availability section is labelled as follows in English and German:
- https://www.coronawarn.app/en/faq/#availability "Availability" (EN)
- https://www.coronawarn.app/de/faq/#availability "Verfügbarkeit" (DE)
This suggestion is made after answering https://github.com/corona-warn-app/cwa-app-android/issues/4443 "where I can find the …
> Move FAQ "Where can I get the app?" to start of Availability section

- cypress/integration/blog_spec.js
- cypress/plugins/index.js
- cypress/support/index.js
- package-lock.json
- package.json
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/2074 "Obsolete references to cypress-plugin-snapshots" by removing the old, incompatible and unused references to cypress-plugin-snapshots from: 
- [cypress](https://github.com/corona-warn-app/cwa-website/tree/master/cypress) subdirectories of [cwa-website](https://github.com/corona-warn-app/cwa-website) and from
- [package.json](https://github.com/corona-warn-app/cwa-website/blob/master/package.json) and [package-lock.json](https://github.com/corona-warn-app/cwa-website/blob/master/package-lock.json)
The following commands should run successfully to completion:
```
npm install
npm run test:prepare
npm test
```
~~(Apart from the known issue of bad links described in …
> Remove unused cypress-plugin-snapshots references in code

- src/data/eventregistration_de.json
Due to issue #2138, I fixed the broken link by removing the blank space and adding one more dot to the url.
> Fix broken link  on '/de/eventregistration/'

- cypress/integration/pages/eventRegistration.js
Due to issue #2139, I changed the expected width in the event registration test to 827 so it doesn´t fail.
> Fixed the event registration test

- src/partials/page-faq.html
This PR implements the change suggested in issue https://github.com/corona-warn-app/cwa-website/issues/2163 "nbsp HTML entity cannot be put into FAQ title".
It changes the [src/partials/page-faq.html](https://github.com/corona-warn-app/cwa-website/blob/master/src/partials/page-faq.html) partials page which processes FAQ json input through Panini, so that the contents of the "title" field are not escaped.
This means that HTML entities such as `&nbsp;` are passed through one-to-one into the HTML. Before this change the `&` character was being escaped in title text with the effect that `&nbsp;` appeared literally in the title instead of being used as a non-breaking space.
Text in the "textblock" field was already set up not to be escaped, so this change brings the two fields - "title" and …
> Prevent escaping in FAQ title

- blog/2021-12-15-handlungsempfehlung-rote-kachel/index_de.md
This PR corrects some links in 
https://www.coronawarn.app/de/blog/2021-12-15-cwa-red-tile-guidance/ "Was tun bei einer roten Kachel?"
as described in issue https://github.com/corona-warn-app/cwa-website/issues/2198.
- remove jsessionid
- make absolute links relative
- hide literal target of links for www.coronawarn.app
- correct some other minor errors
> Fix links in Rote Kachel blog DE

- blog/2021-12-20-cwa-2-15/index.md
This PR corrects some text issues in the [English language Blog announcement for CWA 2.15](https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/) concerning typos, grammar and untranslated German text.
> Typos and translations in EN 2.15 blog

- src/assets/js/analyse/chart/options.js
Due to issue #2149 I have added a header and a separator for '7 day moving' to split it from 'daily'
**English version**
**German version**
> Create header and separator for '7 day moving' in Analysis page

- blog/2021-12-15-handlungsempfehlung-rote-kachel/index.md
This PR resolves issue #2229 "Links in "What should you do if you see a red tile?" (EN)". It aligns https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/ with the changes made in the equivalent German language blog https://www.coronawarn.app/de/blog/2021-12-15-cwa-red-tile-guidance/ (see PR #2202).
> Update links in red tile blog (EN)

- src/data/screenshots.json
In https://www.coronawarn.app/en/screenshots/ "Take a Look (Version 2.15)" this PR changes the term "testing partner" in the sentence "The result of the certificate check is transferred to the booking system by the testing partner." to "validation service".
This also conforms to the term used in the blog https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/ "Corona-Warn-App simplifies certificate checks when booking tickets".
"Testing partner" may otherwise be confused with a partner who tests a person for an infection through a PCR or Rapid Antigen Test.
[Guidelines on the use of Digital Covid Certificates in traveller and online booking scenarios](https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_traveller-onlinebooking_en.pdf) - Section 3 Booking and …
> Use term "validation service" in 2.15 screenshots

- blog/2020-09-04-cwa-1-3-post/index.md
- blog/2021-01-28-cwa-1-11/index.md
- blog/2021-02-23-risk-calculation/index.md
- blog/2021-03-04-cwa-1-13/index.md
- blog/2021-03-19-parameteraenderung-risikoberechnung/index.md
- blog/2021-04-16-anpassung-risikoberechnung/index.md
- blog/2021-05-12-cwa-2-2/index.md
- blog/2021-06-10 CWA 2.3 digitaler Impfnachweis/index.md
- blog/2021-06-24 CWA 2.4 Testzertifikat/index.md
- blog/2021-06-29-twitter-account/index.md
- blog/2021-10-06-cwa-2-11/index.md
- blog/2021-10-11-wichtigste-Funktionen/index.md
- blog/2021-10-19-cwa-2-12/index.md
- blog/2021-11-03-cwa-2-13/index.md
- blog/2021-11-04-booster-notifications/index.md
- blog/2021-11-15-cwa-recalled-certificates/index.md
- blog/2021-11-22-cwa-2-14/index.md
- blog/2021-12-20-cwa-2-15/index.md
This PR harmonizes the English language naming of RKI to use the official name "Robert Koch Institute" in blog postings on https://www.coronawarn.app/en/blog/.
It resolves the issue #2226 "Inconsistent full name of RKI in EN blogs".
> Use "Robert Koch Institute" in EN blogs

- blog/2021-12-15-handlungsempfehlung-rote-kachel/index.md
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/2236 "Link to UK Government site in blog" by replacing the link https://www.gov.uk/government/news/public-reminded-to-let-in-fresh-air-when-meeting-others-indoors-to-reduce-the-spread-of-covid-19 to a page of the UK Government by https://www.zusammengegencorona.de/en/ansteckung-mit-corona-so-wird-das-coronavirus-uebertragen/ from the German Federal Ministry of Health.
It changes the blog page https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/ "What should you do if you see a red tile?".
> Link blog to risk reduction information from BMG

- gulpfile.js
This PR resolves the issue https://github.com/corona-warn-app/cwa-website/issues/2248 "Long rebuild time for watched blog change".
It modifies [gulpfile.js](https://github.com/corona-warn-app/cwa-website/blob/master/gulpfile.js) by excluding:
```
PATHS.blogOutputs
PATHS.blogOutputs + '*'`
```
from being watched. This is equivalent to excluding:
```
src/pages/{de,en}/blog/*-*-*-*/
src/pages/{de,en}/blog/*-*-*-*/*
```
Although the problem is not so noticeable for the science blogs, because there are not so many of them (only 4 at this time), the issue is also corrected for this set of blogs by similarly excluding the files related to PATHS.blogScienceOutputs which translates effectively to excluding:
```
src/pages/{de,en}/science/*-*-*-*/
src/pages/{de,en}/science/*-*-*-*/*
```
These are …
> Prevent blog and science blog changes causing rebuild delays

- src/data/faq.json
- src/data/faq_de.json
This PR fixes an empty placeholder in the `rat_what_if_positive_result` FAQ entry.
Preview of the change:
---
**Closes #2254**
> Fix placeholder in FAQ entry (Addresses #2254)

- src/data/faq.json
This PR removes a workaround which was put in place when the left menu for FAQ section names did not scroll.
It changes the section title from "Vaccination Cert." to "Vaccination Certificate". This matches the German "Impfzertifikat" and the line above, which says "Test Certificate".
This is a cosmetic change only.
> Write out Vaccination Certificate in full for FAQ section title

- blog/2021-11-22-cwa-2-14/index_de.md
This PR fixes one abbreviation in the German-language blog https://www.coronawarn.app/de/blog/2021-11-22-cwa-2-14/
- "Abb. 4: Die App kann maximal einen Schnelltest und einen PCR-Test gleichzeitig verwalten. Wenn Nutzer z. B. einen weiteren PCR-Test registrieren, wird der erste PCR-Test in den Papierkorb verschoben."
See also issue https://github.com/corona-warn-app/cwa-website/issues/1689 and [DIN 5008](https://de.wikipedia.org/wiki/DIN_5008#Abk%C3%BCrzungen_(Abschnitt_4.5)).
> Add non-breaking space to abbreviation in blog

- src/assets/js/analyse/chart/options.js
I created this PR to solve issue #2287, that tag shouldn't exist. It appears from PR #2212, the modification I made to separate the data. Now it's fixed, sorry for not realizing that mistake.
Some screenshots with the error fixed:
> Fix analysis tag bug

- blog/2021-11-04-booster-notifications/index_de.md
This PR follows on from issue https://github.com/corona-warn-app/cwa-website/issues/2013 "Links to rki vaccination page in Booster blog".
It changes the link in https://www.coronawarn.app/de/blog/2021-11-04-cwa-booster-notification/ "Corona-Warn-App informiert zu Booster-Impfungen" to https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html "STIKO-Empfehlung zur COVID-19-Impfung".
This target link is already used in the English language blog https://www.coronawarn.app/en/blog/2021-11-04-cwa-booster-notification/ "Corona-Warn-App notifies users about a booster vaccination", so the change aligns the two language versions of the blog.
The text is not changed, only the link. The new link is better suited to provide the information being looked for. The …
> Change booster blog link to STIKO recommendations

- src/assets/js/analyse/chart/options.js
Due to issue #2325 I have created this PR. This fix the capitalization error shown in analysis page when is not data to show or the user deactivate all the options to show in a graphic. The text used is from @MikeMcC399. Thanks, as always!
> Fix analysis typo when is not data to show or user deactivate it

- src/data/faq.json
- src/data/faq_de.json
R 2.16 FAQ - update #root_detection_android  #2300.
- changed wording and added a sentence to #root_detection_android DE & EN
**PREVIEW:**
---
Internal Tracking ID: [EXPOSUREAPP-11102](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11102)
> R 2.16 FAQ -  update #root_detection_android

- blog/2022-01-17-cwa-2-16/index.md
- blog/2022-01-17-cwa-2-16/index_de.md
This PR converts a link in
https://www.coronawarn.app/en/blog/2022-01-17-cwa-2-16/ from
https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4/ (absolute) to
/en/blog/2021-06-24-cwa-version-2-4/ (relative) for better maintainability.
Similarly for the German language blog
https://www.coronawarn.app/de/blog/2022-01-17-cwa-2-16/ from
https://www.coronawarn.app/de/blog/2021-06-24-cwa-version-2-4/ (absolute) to
/de/blog/2021-06-24-cwa-version-2-4/ (relative) for better maintainability.
Also, since it was a very minor point I added missing quote character in the English language blog  after `“2G certificate` to match the German blog where this term was in quotes.
> Make link in 2.16 blog to 2.4 blog relative

- blog/2022-01-17-cwa-2-16/index.md
This PR corrects the language of the timestamp on the English language blog
- https://www.coronawarn.app/en/blog/2022-01-17-cwa-2-16/ "Corona-Warn-App version 2.16 shows users’ current status evidence"
from
"Hanna Heine, 10 Uhr, on January 17, 2022"
to
"Hanna Heine, 10 am, on January 17, 2022"
"Uhr" is German and does not belong on a English blog page.
> Change 2.16 EN blog timestamp from "Uhr" to "am"

- blog/2022-01-21-cwa-uhrzeit-rote-kachel/index.md
- blog/2022-01-21-cwa-uhrzeit-rote-kachel/index_de.md
This PR adds spaces where two words have run together in:
- https://www.coronawarn.app/en/blog/2022-01-21-cwa-uhrzeit-rote-kachel/ "Warum zeigt die Corona-Warn-App bei einer roten Kachel die genaue Uhrzeit und den Ort der Begegnung nicht an?" and
- https://www.coronawarn.app/de/blog/2022-01-21-cwa-uhrzeit-rote-kachel/ "Warum zeigt die Corona-Warn-App bei einer roten Kachel die genaue Uhrzeit und den Ort der Begegnung nicht an?"
"Bestandteilbei" => "Bestandteil bei" 
"einemregelmäßigen" => "einem regelmäßigen"
were missing spaces.
> Typo corrections in 2022-01-21 blog

- README.md
This PR updates the recommended version of [Node.js](https://nodejs.org/en/) in the [README.md](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) file from 14.18.2 to 14.18.3.
The GitHub virtual environment [Ubuntu 20.04 LTS](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md) now uses the Node.js version 14.18.3 of the [Node.js 14 (lts/fermium)](https://nodejs.org/download/release/latest-fermium/) release as listed in the [Cached Tools: Node.js section](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#nodejs) of the virtual environment configuration.
> Update README to Node.js 14.18.3

- src/data/faq.json
- src/data/faq_de.json
This PR removes the wrong information that the TAN hotline is not available on German national holidays.
---
Addresses https://github.com/corona-warn-app/cwa-hotline/issues/14#issuecomment-1019152190.
> Remove wrong information reg. TAN hotline

- src/data/faq.json
- src/data/faq_de.json
This PR adds ":" to the `international_phone_numbers` FAQ entry.
See https://github.com/corona-warn-app/cwa-website/pull/2368#issuecomment-1019248073.
> Add ":" to `international_phone_numbers`

- src/assets/js/analyse/fullscreen.js
In this PR I have solved the [problem commented](https://github.com/corona-warn-app/cwa-website/pull/2360#issuecomment-1017420086) in my last PR (#2360) related to Analysis.
Now, when we resize the screen using the mobile breakpoint, the graph height will adapt to the window.
> Fix responsive mobile breakpoint graphs in Analysis

- blog/2022-02-02-cwa-2-17/index.md
- blog/2022-02-02-cwa-2-17/index_de.md
This PR fixes broken links in
- https://www.coronawarn.app/en/blog/2022-02-02-cwa-2-17/ "Booster vaccination statistics, date of deletion in recycle bin, and link to social media channels"
- https://www.coronawarn.app/de/blog/2022-02-02-cwa-2-17/ "Statistik zur Auffrischimpfung, Link zu Social-Media-Kanälen und Löschdatum im Papierkorb"
to the blog posts
- https://www.coronawarn.app/en/blog/2021-11-03-cwa-version-2-13/ and
- https://www.coronawarn.app/de/blog/2021-11-03-cwa-version-2-13/
respectively.
With this fix, the pages no longer produce a 404 error. The Cypress test suite also succeeds once again.
> Fix broken links to 2.13 blog

- src/data/faq.json
- src/data/faq_de.json
This PR updates the text of the FAQ entry `encounter_deletion`. It makes the text general, so that the FAQ is not specific to low risk encounters anymore.
<details>
<summary>Preview of the change</summary>
| German | English | 
|---|---|
|![DE](https://user-images.githubusercontent.com/67682506/151957181-8aeee869-5072-498e-afb8-4b51b76b20fb.png)| ![EN](https://user-images.githubusercontent.com/67682506/151957187-4571f8d8-dcbd-432f-9093-7d1deeb3e3f4.png)|
</details>
> Make "encounter_deletition" general for low and increased risk encounters

- src/data/analyse_de.json
- src/data/analyse_en.json
- src/partials/page-analyse.html
> Added alt text to external image

- src/data/faq.json
- src/data/faq_de.json
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/2547 "FAQ root detection android version wording" by correcting the FAQ text as follows:
---
Change the sentence in https://www.coronawarn.app/en/faq/#root_detection_android "[Google/Android]: Why do I receive a notification regarding administrator permissions (root permissions)?" to:
"These warnings can be stopped in version 2.16 and later until the next update of the app."
---
Change the sentence in https://www.coronawarn.app/de/faq/#root_detection_android "[Google/Android]: Warum erhalte ich eine Benachrichtigung bezüglich Administrator-Berechtigungen (Root-Berechtigungen)?" to:
"Diese Warnungen können ab Version 2.16 bis zum nächsten Update der App unterdrückt werden.
> Change FAQ root detection wording

- src/data/accessibility_de.json
This PR changes the "Bundesministerium" into genitive case in marked up in green in the following screenshot:
This affects:
- https://www.coronawarn.app/de/accessibility/
- https://www.coronawarn.app/de/accessibility/#android
- https://www.coronawarn.app/de/accessibility/#ios
> Correct grammar for DE accessibility statement

- cypress/integration/check_links.js
- This PR resolves the regression in PR https://github.com/corona-warn-app/cwa-website/pull/2434 which reverted the fix from PR #2554.
- The re-opened issue https://github.com/corona-warn-app/cwa-website/issues/2490 is resolved by this PR.
After applying this PR the Cypress test `check_links.js` no longer fails with
```
[RESPONSE 503] https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1 on 'http://localhost:8000/de/blog/2021-08-05-statistictiles' 
[RESPONSE 503] https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1 on 'http://localhost:8000/en/blog/2021-08-05-statistictiles'
```
in `broken_links_result.txt`. Instead all tests pass.
```
npm run test:prepare
npm run test:open
```
select `check_links.js` in Cypress console
Ensure that all tests pass and that there are no failures …
> Reapply checklinks exception for wiley.com

- src/data/faq.json
- src/data/faq_de.json
This PR corrects issue https://github.com/corona-warn-app/cwa-website/issues/2588 "Bad link to explanatory video".
The non-working video link
`<video src='../../assets/video/erklaerfilm_en.mp4'`
is replaced by
`<video src='/assets/video/erklaerfilm_en.mp4'` (EN)
Correspondingly for the German-language link
1. Open https://www.coronawarn.app/en/faq/results/#in_a_nutshell in web browser
2. Scroll down to "Explanatory video"
3. Confirm that video shows the CWA logo and can be played
1. Open https://www.coronawarn.app/de/faq/results/#in_a_nutshell in web browser
2. Scroll down to "Erklärvideo"
3. Confirm that video shows the CWA logo and can be played
> Correct links to "Explanatory video"

- src/data/faq.json
- src/data/faq_de.json
Replaced the outdated list of data in the personal_data FAQ section with a link to the privacy policy in accordance with the details from #1729 .
Affected Sections:
DE: https://www.coronawarn.app/de/faq/#personal_data
**Before**
**After**
EN: https://www.coronawarn.app/en/faq/#personal_data
**Before**
**After**
---
Internal Tracking ID: [EXPOSUREAPP-12410](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12410)
> Personal Data FAQ Update

- src/partials/page-faq.html
This PR is to solve a format issue about topic selector in FAQ homepage.
**Before**
**After**
> Fix format topic selector's option in FAQ page

- src/assets/js/app.js
With this PR, some links broken specified in #2582 would be fixed.
- faq/#glossary or faq/results/#glossary will redirect and filter automatically the glossary section
- clicking section links from bottom FAQ homepage or just getting the URL from the aside to share and visiting it, will filter the section correctly
In this PR has been restored also the filter functionality clicking on section titles, broken in some accessibility change.
> Fix glossary redirect and actual sections links

- gulpfile.js
This commit PR the current iOS & Android app version to 2.20.3.
---
GitHub releases:
- iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.20.3
- Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.20.3
> Bump current iOS & Android app version

- src/partials/page-analyse.html
Initial Issue #2458
The Pop-up layout on the dashboard page is broken again since PR WCAG fixes #2644 was merged. I have added the missing double quotes again.
> added missing double quote

- src/data/faq.json
- This PR reapplies a missing fix from PR https://github.com/corona-warn-app/cwa-website/pull/2416 which was accidentally reverted by PR https://github.com/corona-warn-app/cwa-website/pull/2434.
- According to the (re-opened) issue https://github.com/corona-warn-app/cwa-website/issues/2384, links to https://github.com/corona-warn-app/cwa-documentation/tree/master should target https://github.com/corona-warn-app/cwa-documentation/tree/main.
> Correct link to cwa-documentation branch

- cypress/integration/check_anchor_links.js
Updated check_anchor_links.js to allow for testing of "/en/faq/results/" and "/de/faq/results/".
See https://github.com/corona-warn-app/cwa-website/issues/2613#issuecomment-1085418447
> Update check_anchor_links.js for new FAQ

- src/assets/js/app.js
Fix for Issue #2652
The on-click listener of the section headers use the URL parameter **topic** for updating the results, but if you click on a section-header the URL parameter doesn't changes to the clicked topic. So if somebody search in **All** topics and then click on a section header the result counter is calculated wrong.
So i pass the clicked topic the the **updateResult()** funtion.
> use current topic in on-click event listener for section headers

- src/data/faq.json
- src/data/faq_de.json
As part of PR https://github.com/corona-warn-app/cwa-website/pull/2656#issue-1189294825 I was able to run the check_anchor_links.js Cypress test for /faq/results/ and found a number of broken links.
Creating this PR to update these broken links to the corresponding new link.
Before:
After:
> /faq/results broken links updates

- src/data/faq.json
- src/data/faq_de.json
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/2678 "Google controlled history not reduced to 10 days". It 
- removes the added text "(10 days since version 2.20)" from https://www.coronawarn.app/en/faq/results/#keys_matches "What do the exposure check logs show?" and
- removes the added text "(10 Tage ab Version 2.20)" from https://www.coronawarn.app/de/faq/results/#keys_matches "Was bedeutet die Überprüfung auf mögliche Begegnungen?"
Effectively this reverts the changes made to the above FAQ articles by:
- PR https://github.com/corona-warn-app/cwa-website/pull/2540
> Correct #keys_matches: GAEN still keeps 14 day's keys

- src/data/faq.json
- src/data/faq_de.json
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/2671 "FAQ #news backwards compatibility" by creating a new FAQ entry with `#news` as anchor. It also guides the user to where to find news about the app in:
1. the Blog https://www.coronawarn.app/en/blog/ (EN/DE) and
2. in the Twitter channel https://twitter.com/coronawarnapp (predominantly DE)
with an additional link to [#where_to_get](https://www.coronawarn.app/en/faq/results/#where_to_get) containing links to the App Store and Google Play Store.
The FAQ article is placed at the top of the list App Features > [Other features](https://www.coronawarn.app/en/faq/results/#other_features).
---
EN
---
DE
> Create new FAQ #news

- src/data/faq_redirects.json
- This PR implements the suggestion from https://github.com/corona-warn-app/cwa-website/issues/2661#issuecomment-1087690698
The following FAQ redirects are added
From anchor | To anchor
--- | ---
#vac_cert_index |  #vac_cert
#vac_cert_booster | #vac_cert
#test_cert_index | #test_cert
#check_in_index | #check_in
This means that for instance a bookmark https://www.coronawarn.app/en/faq/#vac_cert_index from the old FAQ format will redirect to https://www.coronawarn.app/en/faq/results/#vac_cert.
The original anchors were not carried over from the old FAQ format to the new FAQ format, because the corresponding content was deleted, so this ensures that any external bookmarks using these links will continue to direct the user to the most appropriate content.
> Add FAQ Q&A index redirects

- src/data/faq_redirects.json
Added redirect for anchor 'notification' to fix Issue 'FAQ notification backwards compatibility #2672'
> added redirect for #notification anchor

- src/data/simple-language_de.json
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/2571 "Wrong text for FAQ simple language".
It corrects the definition for FAQ on https://www.coronawarn.app/de/simple-language/#usage as shown in the following screenshot:
The text is:
"Auf der Internet-Seite gibt es Antworten zu den häufig gestellten Fragen der Corona-Warn-App."
> Correct simple language FAQ definition

- src/assets/scss/_nav.scss
Due to the issue: #2690 I made nav-aside more bigger.
- Before:
- After:
> Make nav-aside bigger

- src/assets/js/app.js
due to an issue [#2693](https://github.com/corona-warn-app/cwa-website/issues/2693) I fix the aside scroll in FAQ's results
here is a video showing the problem solved: https://user-images.githubusercontent.com/57190230/161992901-9a4b820c-665c-4554-8ed2-7fbaa6ba7aaf.mp4
> Fix aside scroll in FAQ's results

- src/data/faq_de.json
- src/partials/text-component.html
One change of #2449 caused the text describing the versions changes on the screenshots page to disappear. This PR reverts that change to restore the text.
In addition, I have corrected an abbreviation in the recently published FAQ "dcc_ri_429", so that it matches [DIN 5008](https://de.wikipedia.org/wiki/DIN_5008#Abk%C3%BCrzungen_(Abschnitt_4.5)) @MikeMcC399 https://github.com/corona-warn-app/cwa-website/pull/2720#issuecomment-1094584913
> Restore screenshot version text

- science/2021-06-15-science-blog-1/index_de.md
- science/2021-07-08-science-blog-2/index_de.md
- science/2021-08-02-science-blog-3/index_de.md
- science/2021-10-15-science-blog-4/index_de.md
- science/2022-03-03-science-blog-5/index_de.md
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/2725 "German abbreviations non-conformant to DIN 5008 in blogs" in https://www.coronawarn.app/de/science/, the German language Science Blog.
It changes the following abbreviations:
- `u.a.` => `u.&nbsp;a.`
- `d.h.` => `d.&nbsp;h.`
- `z.B.` => `z.&nbsp;B.`
in the following Science Blog articles:
- https://www.coronawarn.app/de/science/2021-06-15-science-blog-1/
- https://www.coronawarn.app/de/science/2021-07-08-science-blog-2/
- https://www.coronawarn.app/de/science/2021-08-02-science-blog-3/
- https://www.coronawarn.app/de/science/2021-10-15-science-blog-4/
- https://www.coronawarn.app/de/science/2022-03-03-science-blog-5/
> Correct Science Blog DE abbreviations

- blog/2021-12-20-cwa-2-15/index.md
- blog/2021-12-20-cwa-2-15/index_de.md
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/2745 "Verification Service blog (2.15) has links to deleted FAQs". It removes the references to deleted and (at least temporarily) obsolete FAQ articles in the following blog articles covering the Verification Service, which is on hold with no defined future plan:
- https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/ "Corona-Warn-App simplifies certificate checks when booking tickets", remove links to deleted articles:
- https://www.coronawarn.app/en/faq/#val_service_no_valid_dcc "Why do I get the message that there is no suitable certificate?"
- https://www.coronawarn.app/en/faq/#val_service_result "Why is my certificate not verifiable or not recognized?"
- …
> Remove links to deleted verification service FAQs in 2.15 blog

- src/data/faq_redirects.json
This PR adds a new FAQ redirect  from `check_in_qr_warning` to `check_in`, as the FAQ entry `check_in_qr_warning` has been deleted.
- A FAQ Redirect was added
> Add FAQ redirect from `check_in_qr_warning` to `check_in`

- src/data/faq.json
- src/data/faq_de.json
This PR renames the FAQ entry `val_service_basics`, to reflect that there is only one question answered, and not multiple questions.
- The title of the German FAQ entry https://www.coronawarn.app/de/faq/results/#val_service_basics was changed from "Fragen und Antworten zur Zertifikatsprüfung bei Ticketbuchungen" to "Informationen zur Zertifikatsprüfung bei Ticketbuchungen"
- The title of the English FAQ entry https://www.coronawarn.app/en/faq/results/#val_service_basics was changed from "Questions and answers about certificate verification during ticketing" to "Information on certificate verification during ticketing"
| German | English |
|---|---|
| <img width="1070" alt="German" src="https://user-images.githubusercontent.com/67682506/163427940-dc9ea789-a9f2-49f8-8b46-5c9b9d9ac5e6.png"> …
> Rename  FAQ entry `val_service_basics`

- src/data/faq.json
- src/data/faq_de.json
This PR gives more precise information when a warning can be issued based on a check in in the FAQ entries `check_in_qr_warning_procedure` & `check_in_qr_warning_how`.
- https://www.coronawarn.app/en/faq/results/#check_in_qr_warning_procedure
- https://www.coronawarn.app/de/faq/results/#check_in_qr_warning_procedure
- https://www.coronawarn.app/en/faq/results/#check_in_qr_warning_how
- https://www.coronawarn.app/de/faq/results/#check_in_qr_warning_how
| German | English |
|---|---|
| <img width="1068" alt="German" src="https://user-images.githubusercontent.com/67682506/163433987-0e0e1381-b40d-44bf-b9bb-2d42e9e5e923.png"> | <img width="1068" alt="English" src="https://user-images.githubusercontent.com/67682506/163433980-f58f2293-3609-4050-b2cd-5551ddd778a6.png"> |
---
**Closes #1651**
> More precise information reg. check in warning in FAQ entries `check_in_qr_warning_procedure` & `check_in_qr_warning_how` (Addresses #1651) 

- src/assets/js/app.js
With PR #2647 I implemented a function to count the glossary results and added this function in several places, but I forgot one place. Now the search result counter for the glossary works as expected.
@MikeMcC399 I looked through my issues again, but I couldn't find a corresponding issue. I think I forgot to open an issue for this problem. Thanks for researching.
> count glossary results correctly

- cypress/integration/check_links.js
This PR resolves issue #2767 "Cypress does not test sitemap links" by adding the following to `pages` in [cypress/integration/check_links.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/check_links.js)
- '/de/sitemap/'
- '/en/sitemap/'
`npm run test:open`
select `check_links.js`
check that the sitemap directories `/de/sitemap/` and `/en/sitemap/` are listed in the Cypress log
> Add sitemap to Cypress check_links.js

- src/partials/page-imprint.html
- src/partials/page-privacy.html
- src/partials/page-terms-of-use.html
Follow-up to #2755 and #2752 
In order to make the pages more accessible, headings should follow a sequential, descending order, and shouldn't skip a level. With this PR, this will fix it for
-  https://www.coronawarn.app/en/terms-of-use/
-  https://www.coronawarn.app/en/imprint/
-  https://www.coronawarn.app/en/privacy/
> Fix heading order

- src/data/community.json
- src/data/community_de.json
This PR changes the social media anchor link, so that it works with the link implemented in the app. 
[Social media link in Android repository](https://github.com/corona-warn-app/cwa-app-android/blob/c16276c3037054d09f5f095455735973c3264f1f/Corona-Warn-App/src/main/res/values/links.xml#L73)
[Social media link in iOS repository](https://github.com/corona-warn-app/cwa-app-ios/blob/b65edc14f30cc8654cec94afaab2222a03c10248/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings#L11)
---
Internal Tracking ID: [EXPOSUREAPP-12846](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12846)
> Change social media anchor link

- blog/2020-12-15-iOS12x-statement/index.md
- blog/2022-03-16-cwa-2-19/index.md
- blog/2022-03-30-cwa-2-20/index.md
- blog/2022-04-19-cwa-2-21/index.md
This PR resolves issue #2783 "Harmonize on app name in EN version announcement blogs" by replacing "Corona warning app" by "Corona-Warn-App" in all English language blogs where the term is specifically referring to RKI's CWA app.
No change is made where "Corona warning app" is used in blogs in a generic sense.
> Use standard name "Corona-Warn-App" in EN blogs

- src/data/screenshots-archive-2-20.json
- src/data/screenshots.json
This PR corrects typos in the Screenshot description text for:
- https://www.coronawarn.app/en/screenshots/#ios_screenshots
- https://www.coronawarn.app/en/screenshots/#android_screenshots
- https://www.coronawarn.app/en/screenshots-archive/2-20.html#ios_screenshots
- https://www.coronawarn.app/en/screenshots-archive/2-20.html#android_screenshots
> Correct screenshot text typos

- .github/workflows/deploy-master.yml
Trying to fix
```
E: The repository 'https://cli-assets.heroku.com/apt ./ InRelease' is not signed.
```
in
https://github.com/corona-warn-app/cwa-website/runs/6194463380?check_suite_focus=true#step:3:59
> changing heroku to auto updating standalone

- gulpfile.js
Closes [#19](https://github.com/corona-warn-app/cwa-website/issues/19)
Webpack source maps added.
JS:
CSS:
Internal Tracking ID: [EXPOSUREAPP-12958](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12958)
> added source maps for js/css to production package

- blog/2022-05-04-cwa-2-22/index.md
- blog/2022-05-04-cwa-2-22/index_de.md
This PR corrects text in the blog announcements for CWA 2.22
- https://www.coronawarn.app/en/blog/2022-05-04-cwa-2-22/ "CWA 2.22: Rapid test profiles for family members"
- https://www.coronawarn.app/de/blog/2022-05-04-cwa-2-22/ "CWA 2.22: Schnelltest-Profile für Familienmitglieder"
In Android the button to create a rapid test profile, as seen in the screenshots, is labelled:
- "+ RAPID TEST PROFILE" (English)
- "+ SCHNELLTEST-PROFIL" (Deutsch)
The blog texts are aligned in this PR to conform to the respective screenshots showing creation of an RTP. In the English version it was confusing to read the description of the label in complete lower case in the text as "+ rapid test profile" when it appears in the app completely in upper case as "+ RAPID TEST PROFILE".
> Change Android RTP button label to upper case in Blog 2.22 text

- cypress/integration/mime.js
This PR implements the enhancement request #2886 "Improve Cypress testing against non-functioning app.js" by checking the mime type of `/assets/js/app.js` to include `/javascript`. In addition, the mime type of `/assets/css/style.css` is checked to include `text/css`.
According to https://www.rfc-editor.org/rfc/rfc9239 `application/javascript` is obsolete, however [browser-sync](https://www.npmjs.com/package/browser-sync) seems not to respect this and responds with
`Content-Type: application/javascript; charset=UTF-8`. This applies when running a local test copy of the web.
A simple compromise to accept both `application/javascript` (browser-sync) and `text/javascript` (production webserver) is to only check for `/javascript`, which allows the test to pass in both environments.
From a …
> Add Cypress test for mime types

- blog/2021-05-11-How-to-Schnelltest-Partner/index.md
- blog/2021-05-11-How-to-Schnelltest-Partner/index_de.md
- blog/2022-01-11-omikron/index.md
- blog/2022-01-21-cwa-uhrzeit-rote-kachel/index.md
This PR resolves issue #2683 "Missing blog translations into English" by replacing promises that an English translation may come soon using the replacement text "_German version only_".
Also one typo regarding "*dm drogerie-märkte" is corrected.
> EN blog no translation - change to "German version only"

- src/data/faq.json
- src/data/faq_de.json
This PR is for insert a new FAQ.
**Ich erhalte die Meldung, dass die Gültigkeit eines Zertifikats bald abläuft. Was muss ich tun?**
Die technische Gültigkeit der digitalen COVID-Zertifikate läuft nach 365 Tagen automatisch ab. Für alle relevanten Zertifikate erhalten Sie dazu 28 Tage vor Ablauf eine Mitteilung in der Corona-Warn-App. Um Ihren Impfstatus weiterhin mit der App nachweisen zu können, müssen die entsprechenden Zertifikate aktualisiert werden. Die dazu notwendige Neuausstellung können Sie demnächst in der App mit wenigen Klicks selbst durchführen.
**I receive a notification that the validity of a certificate is about to expire. What do I have to do?**
The technical validity of COVID digital certificates expires automatically after 365 days. For all relevant certificates, you …
> Insert new FAQ #dcc_replacement_howto

- src/assets/js/app.js
- src/partials/page-faq-results.html
I fixed the issue with glossary articles not showing, when opening a direct link to an article on mobile devices as mentioned in Issue #2914.
> Fixed glossary article not showing, when opening direct link on mobile devices

- .github/workflows/cypress-test-prod.yml
This draft PR partially implements the workflow requested in https://github.com/corona-warn-app/cwa-website/issues/2892 "Add new GitHub Actions workflow carrying out the cypress test suite".
It was suggested in https://github.com/corona-warn-app/cwa-website/issues/2892#issuecomment-1141760610 to run the test regularly.
It uses https://github.com/cypress-io/github-action to run Cypress tests on the production server https://coronawarn.app once a day. The tests selected are the ones in the top level of `cypress/integration`. The problematic test `check_links.js`, which is prone to failure, is already moved down one level to `cypress/integration/hybrid`, and is not selected.
Removing the line `spec: cypress/integration/*.js` would run all tests, if that is desired. …
> Add workflow for Cypress test on production with Chrome

- cypress/fixtures/appToWebLinks.json
- cypress/integration/app_to_web.js
- cypress/support/index.js
This PR implements the enhancement request https://github.com/corona-warn-app/cwa-website/issues/2909 "Extend Cypress testing to coronawarn.app links used by CWA app".
The PR:
- adds a new Cypress test `/cypress/integration/app_to_web.js`, which is data-driven from `/cypress/fixtures/appToWebLinks.json` for easier maintenance of any new links which need to be added
- adds a new Cypress command `testFaqRedirect` into `/cypress/support/index.js`. This works around a Cypress issue by returning to the homepage in between testing redirected links.
Links were manually harvested from:
- [links.xml](https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values/links.xml) at the CWA Android 2.23 version level.
- …
> Add Cypress test app_to_web

- blog/2021-12-15-handlungsempfehlung-rote-kachel/index.md
This PR resolves issue  https://github.com/corona-warn-app/cwa-website/issues/2976  "Link failure in red tile blog (EN)".
It removes the failing link to https://www.zusammengegencorona.de/en/ansteckung-mit-corona-so-wird-das-coronavirus-uebertragen/ in the blog article https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/ "What should you do if you see a red tile?".
This paragraph in the English language blog is then equivalent to the German language blog, which already had no link.
> Remove bad link in red tile (EN) blog

- src/assets/scss/_analyse.scss
Due to issue #2966, I had controlled the heading width according to the cancel box width.
https://user-images.githubusercontent.com/44208107/174785325-0429ba5a-ec5d-48c8-8260-ce0067a56316.mp4
---
Internal Tracking ID: [EXPOSUREAPP-13402](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13402)
> Adjust heading width to avoid overlaps cancel box in Dashboard

- src/data/faq.json
- src/data/faq_de.json
This PR resolves issue  https://github.com/corona-warn-app/cwa-website/issues/2978   "Terms for rapid tests in TAN hotline article".
It makes the terms for rapid antigen and rapid PCR tests used in the following articles consistent with the glossary and it links the terms to the glossary.
- https://www.coronawarn.app/en/faq/results/#rat_tan_hotline "Can I share my positive rapid antigen test or rapid PCR test result via the TAN hotline?"
- https://www.coronawarn.app/de/faq/results/#rat_tan_hotline "Kann ich mein positives Antigen-Schnelltest- oder PCR-Schnelltest-Ergebnis über die TAN-Hotline teilen?"
> Test type references for TAN hotline consistency

- cypress/fixtures/appToWebLinks.json
This PR adds a new link
`#eu_dcc_export_error`
to be tested by [cypress/integration/app_to_web.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/app_to_web.js)
- The link was added to CWA Android [release/2.24.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.24.x) through PR https://github.com/corona-warn-app/cwa-app-android/pull/5271 and is included in [v2.24.0-rc.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.24.0-rc.1).
The pre-requisite for a successful test is the creation of the FAQ articles to be finally published under:
- https://www.coronawarn.app/en/faq/#eu_dcc_export_error
- https://www.coronawarn.app/de/faq/#eu_dcc_export_error
On branch [cwa-website/tree/release/2.24](https://github.com/corona-warn-app …
> Add faq anchor #eu_dcc_export_error to Cypress test for release 2.24

- gulpfile.js
This PR bumps the iOS & Android app versions from 2.24.0 to 2.24.1.
--- 
Android release: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.24.1
iOS release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.24.1
> Bump app versions

- cypress/fixtures/appToWebLinks.json
- cypress/integration/app_to_web.js
This PR provides an enhancement update to the Cypress test [cypress/integration/app_to_web.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/app_to_web.js) which tests that links used in the Android and iOS apps are working on the website https://www.coronawarn.app/.
The issue https://github.com/corona-warn-app/cwa-website/issues/3003 "Missing test for app to web blog link" is resolved through the following changes:
1. add a new test for blogs to [cypress/integration/app_to_web.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/app_to_web.js)
2. add a blog test data section `blogEntry` to [cypress/fixtures/appToWebLinks.json](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/fixtures/appToWebLinks.json)
3. …
> Update Cypress test app_to_web.js

- cypress/fixtures/appToWebLinks.json
- cypress/integration/app_to_web.js
This PR implements suggestions from issue  https://github.com/corona-warn-app/cwa-website/issues/3028  "Testing of web links from app".
1. A simple test is added to [cypress/integration/app_to_web.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/app_to_web.js) to check the ability of the FAQ landing page https://www.coronawarn.app/en/faq/ and https://www.coronawarn.app/de/faq/ to access the detailed FAQ page `faq/results`.
2. The alternate blog link `2021-08-05-statistictiles/` is added to [cypress/fixtures/appToWebLinks.json](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/fixtures/appToWebLinks.json)
`npm run test:open`
select `app_to_web.js`
7 tests should run successfully with 0 failures
> Extend Cypress app_to_web.js test spec

- src/data/faq.json
- src/data/faq_de.json
Resolves #2981 
With this PR, any link in the FAQ opens up in a new tab. The changes are quite hard to represent in screenshots since there were many changes in this, however I'd like to explain my method of solving this.
Using the regular expression `<a href='[^']*'>`, any links that **only** contain the `href` attribute were highlighted. The attribute `target='_blank'` was added to all matching results, as suggested in the issue and preceding pull request (#3009).
---
Internal Tracking ID: [EXPOSUREAPP-13506)](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13506)
> Update links: Open all FAQ links in a new tab

- docs/CHANGE_WEBSITE_CONTENT.md
This PR implements the suggestion from https://github.com/corona-warn-app/cwa-website/issues/3034 to document conventions for defining HTML hyperlinks in the website FAQ section.
> Document conventions for FAQ links

- cypress/support/index.js
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3040 "Error in Cypress softAssert error message format".
The formatting characters in the error message are correctly escaped with the backslash character "\":
`data.error.message = '\n\n\t' + data.error.message + '\n\n';`
1. Introduce a temporary error, e.g. in /data/index.json Line 18 change `#howto` to `#how`
2. Execute `npm run test:open`
3. Select `check_anchor_links.js`
4. Check for correctly formatted error message with two blank links before and after the text and a tab before the text `Failed soft assertions... check log above ↑`
> Correct soft assertions message format

- src/data/.gitignore
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3037 "searchable_blogentries missing in .gitignore".
It adds
`searchable_blogentries*.json`
to
https://github.com/corona-warn-app/cwa-website/blob/master/src/data/.gitignore
1. Execute `npm run build`
2. Watch the folder /src/data in VS Code and note that the files
- `searchable_blogentries_de.json` and 
- `searchable_blogentries.json`
are temporarily shown and are greyed out
---
Internal Tracking ID: [EXPOSUREAPP-13674](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13674)
> Add searchable_blogentries*.json to .gitignore

- gulpfile.js
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3043 "sitemap.xml includes unrounded priority 0.3999999999999999" by changing the priority calculation to avoid unintended precision inaccuracies.
The priority calculation is first carried out using whole numbers then divided by 10:
`return (10 - (entry.file.split('/').length - 1) * 2) / 10`
Execute `npm run build`
Examine the file `public/sitemap.xml` in the local cwa-website repository
Check that there are no longer any entries with priority `0.3999999999999999`
Check that the entry for https://coronawarn.app/de/faq/results/ shows priority `0.4`
Check that only priorities `1`, `0.8`, `0.6`, `0.4`, `0.2` and `0` are used
> Correct sitemap priority calculation

- src/data/faq_de.json
This PR corrects the spelling of [Ständige Impfkommission (STIKO)](https://www.rki.de/DE/Content/Kommissionen/STIKO/stiko_node.html) in the German FAQ. There are two "m"s in [Kommission](https://www.duden.de/rechtschreibung/Kommission).
> Correct STIKO typo (Impfkommission)

- src/data/faq.json
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3081 "FAQ Wrong STIKO translation into English".
It changes the name of STIKO in https://www.coronawarn.app/en/faq/results/#vac_cert_booster_info "How do I become aware of booster vaccinations in the context of Corona?" to "Standing Committee on Vaccination".
Reference: [RKI: Standing Committee on Vaccination (STIKO)](https://www.rki.de/EN/Content/infections/Vaccination/Vaccination_node.html).
> Correct STIKO name to "Standing Committee on Vaccination" (EN)

- blog/2022-04-19-cwa-2-21/index.md
- blog/2022-05-04-cwa-2-22/index.md
- blog/2022-06-01-cwa-2-23/index.md
- blog/2022-06-29-cwa-2-24/index.md
- blog/2022-07-27-cwa-2-25/index.md
This PR corrects the English language name of RKI in newer blogs. The official name is "Robert Koch Institute".
There is no hyphen (-) in the English name of RKI, only in the German name.
- https://www.coronawarn.app/en/imprint/
- https://www.rki.de/EN/Service/Imprint/imprint_node.html
> Correct RKI EN name in newer blogs (no hyphen)

- src/data/news_archive_combined.json
This PR resolves https://github.com/corona-warn-app/cwa-website/issues/3096 "404 error for BReg 'CWA: Der Baukasten für Unterstützerinnen und Unterstützer'".
The blog archive entry for [Corona-Warn-App: Der Baukasten für Unterstützerinnen und Unterstützer](https://styleguide.bundesregierung.de/sg-de/basiselemente/programmmarken/corona-warn-app-baukasten/corona-warn-app-der-baukasten-fuer-unterstuetzerinnen-und-unterstuetzer-1756534) is removed, since the corresponding target link no longer exists. (404-Meldung Die von Ihnen gewählte URL kann leider nicht aufgerufen werden.)
After merging this PR the Cypress test [cypress/integration/hybrid/check_links.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/hybrid/check_links.js) will no longer fail with a 404 …
> Remove BReg Baukasten from blog archive

- src/data/screenshots.json
Fixes https://github.com/corona-warn-app/cwa-website/issues/3094#issuecomment-1272086287
> https://www.coronawarn.app/en/screenshots/ includes an incorrectly written date:
> 
> "August 31th, 2022"
> 
> Either
> 
> "August 31st, 2022" (see https://en.wikipedia.org/wiki/English_numerals#Ordinal_numbers) or
> "August 31, 2022"
> 
> would be correct.
---
Internal Tracking ID: [EXPOSUREAPP-14015](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14015) / [EXPOSUREAPP-14093](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14093)
> 2.26 Screenshots: Fix incorrectly written date

- gulpfile.js
The current android release is 13. This PR updates the gulpfile to replace "android.latest-os-version" with 13 instead of 12.
Seemingly, that replacement is currently unused.
---
Internal Tracking ID: [EXPOSUREAPP-14104](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14104)
> update gulpfile.js android.latest-os-version to 13

- src/data/screenshots-archive-2-26.json
- src/data/screenshots-archive-2-26_de.json
- src/pages/de/screenshots-archive/2-26.html
- src/pages/en/screenshots-archive/2-26.html
With #3131, the screenshots for version 2.27 have been released. However, the screenshots for 2.26 were not archived and accessing https://www.coronawarn.app/de/screenshots-archive/2-26.html or https://www.coronawarn.app/en/screenshots-archive/2-26.html currently leads to a 404 error.
With this PR, this is fixed
> Update screenshots: Add 2.26 archive

- src/assets/js/analyse/chart/config.js
When looking at the "Sharing behaviour" tile, specifically the "QR codes" and "teleTANs" section, the order of "Shared" and "Not Shared" differs between "Daily" and any other option. While "Shared" is at the bottom of each bar in the "Daily" view, it is at the top of the bar in any other view.
To fix this, we have changed the order of all other views to align with the daily view.
---
Internal Tracking ID: [EXPOSUREAPP-14142](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14142)
> Update Dashboard: Change order on statistics

- cypress/fixtures/appToWebLinks.json
This PR resolves https://github.com/corona-warn-app/cwa-website/issues/3146 "Cypress test fails redirect check" by making changes to the source of data-driven testing in [cypress/fixtures/appToWebLinks.json](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/fixtures/appToWebLinks.json).
In the `faqRedirect` section, the anchor `#vac_cert_booster` entry is changed to test for redirection to `#vac_booster_basics`.
Execute
`npm run test:open`
select `app_to_web.js`
The test should run successfully.
After merging and waiting for the daily run of [.github/workflows/cypress-test-prod.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/cypress-test-prod.yml), check also the status of the Action …
> Update Cypress check for #vac_cert_booster redirection

- cypress/fixtures/copy/stringDe.json
- cypress/fixtures/copy/stringEn.json
This PR changes the test data for [faq.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/faq.js) to make it less sensitive to the exact text in https://www.coronawarn.app/en/faq/results/#further_details.
Submitting first as draft until Cypress tests completed.
- This should also fix the issue in PR https://github.com/corona-warn-app/cwa-website/pull/3151
Internal Tracking ID: [EXPOSUREAPP-14167](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14167)
> Make faq test less senstive for statistics entry

- cypress/fixtures/appToWebLinks.json
- cypress/integration/app_to_web.js
This PR refactors the Cypress test [cypress/integration/app_to_web.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/app_to_web.js) section which checks FAQ redirects. The source data of the redirect source and destination anchors stored in [appToWebLinks.json](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/fixtures/appToWebLinks.json) is restructured for readability.
In the original submission of this data the relationship between redirect source and destination was displayed by keeping the data pair on one line. Unfortunately if the json file is reformatted using standard editor tools, then this relationship is lost. This affects readability only, not functionality.
To make sure that the redirect data is still readable after editor …
> Refactor faqRedirect test

- cypress/fixtures/appToWebLinks.json
This PR carries out housekeeping for the [appToWebLinks.json](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/fixtures/appToWebLinks.json) data source for the Cypress test [cypress/integration/app_to_web.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/app_to_web.js).
1. The comment field `appVersionLast` is updated to 2.28 to show that the file has been prepared for the upcoming release
2. The `#mask_rules` entry, which was added for the 2.27 release, is moved into alphabetical order for better readability and maintenance
Note that although the use of the FAQ anchor `#quarantine_measures` is planned to be removed in the CWA 2.28 release, it stays in the [appToWebLinks.json](https://github.com/corona-warn-app/cwa-website/blob/master/cypr …
> Update appToWebLinks.json for 2.28 release

- .github/workflows/build.yml
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3160 "Build workflow shows deprecation notice" by updating 
[.github/workflows/build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml):
- `actions/checkout@v2` to `v3`
- `actions/setup-node@v2` to `v3`
--
Internal Tracking ID: [EXPOSUREAPP-14216](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14216)
> Update build workflow actions to v3

- .gitignore
This PR cleans up `.gitignore` entries affected by Cypress and resolves issue https://github.com/corona-warn-app/cwa-website/issues/3166 "Cypress entries in .gitignore".
It makes the following changes to [.gitignore](https://github.com/corona-warn-app/cwa-website/blob/master/.gitignore):
- Add `cypress/downloads/` 
- Remove `cypress/logs/broken_anchor_links_result.txt` and `cypress/logs/broken_links_result.txt`
Execute `npm test`
Execute `git status` and ensure that no new temporary files are marked.
View local repository with VS Code and check that the directories:
- `cypress/downloads`
- `cypress/logs`
are greyed out (to indicate that they are ignored by git)
---
Internal Tracking ID: [EXPOSUREAPP-14225](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14225)
> Modify .gitignore for Cypress

- README.md
This PR updates the reference to Node.js 16 in the [README.md: Requirements](https://github.com/corona-warn-app/cwa-website/blob/master/README.md#requirements) file section.
According to https://github.com/nodejs/release#release-schedule Node.js 16 is now in Maintenance status instead of the previous Active status. The download link for v16 is no longer on the main page, so the appropriate link to the download page for the latest node v16 version is added.
Node.js 18.x now becomes the Active LTS version (see https://nodejs.org/en/blog/release/v18.12.0/ from Oct 25, 2022).
Note that the GitHub Ubuntu runners, including [`ubuntu-latest` or `ubuntu-20.04`](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md) are currently still using node 16 (16.18.0) at this …
> Update reference to Node.js 16 (Maintenance)

- .github/workflows/build.yml
- .github/workflows/deploy-master.yml
- README.md
- This PR replaces PR https://github.com/corona-warn-app/cwa-website/pull/3187
- It implements the suggestion from https://github.com/corona-warn-app/cwa-website/issues/3186.
The web builds on GitHub using Node.js 18. Locally the web can still be built without errors on Node.js 16, although users should preferably also migrate to using Node.js 18 locally to avoid future issues.
The following changes are made:
1. Workflow: change `node-version:` from `'lts/gallium'` to `'lts/hydrogen'`
2. Update [README: Requirements](https://github.com/corona-warn-app/cwa-website/blob/master/README.md#requirements) to refer to Node.js 18
---
Internal Tracking ID: [EXPOSUREAPP-14247](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14247)
> Migrate cwa-website to Node.js 18 (Active LTS)

- gulpfile.mjs
- package-lock.json
- package.json
This PR implements the suggestion https://github.com/corona-warn-app/cwa-website/issues/3190 "Migrate npm yargs package to v17".
It installs the latest npm [yargs](https://www.npmjs.com/package/yargs) package 17.6.0.
It changes the import of `yargs` in the [gulpfile.mjs](https://github.com/corona-warn-app/cwa-website/blob/master/gulpfile.mjs) to make it compatible with the ECMAScript modules (ESM) interface introduced in [yargs v16.0.0](https://github.com/yargs/yargs/releases/tag/v16.0.0)
```js
import npmYargs from 'yargs';
import { hideBin } from 'yargs/helpers';
const yargs = npmYargs(hideBin(process.argv));
```
Test `gulp` script commands:
1. `npm run start-fast`
2. `npm run start`
3. `npm run dev`
4. `npm run build`
5. `npm run start-server`
Internal Tracking ID: …
> Migrate npm yargs package to v17.6.0 (latest version)

- gulpfile.mjs
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3194 "Experimental json import warning from build"
It changes the method used to import a `json` file in an ESM environment from using an experimental feature to using a supported `Node.js` feature.
Adding the lines:
```js
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
```
before the original code from the CommonJS environment:
```js
const analyseConfig = require('./src/data/analyse.json');
```
resolves the issue.
`npm run build` should run successfully and it should not output the following message:
`(node:21804) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time`
> Fix experimental json import in gulpfile.mjs

- package-lock.json
- package.json
This PR uninstalls gulp plugins which are not used, as described in issues:
- https://github.com/corona-warn-app/cwa-website/issues/3192
- https://github.com/corona-warn-app/cwa-website/issues/3193
After syncing the installed npm packages with `npm ci` then
`npm run build` and
`npm test`
should show no errors.
---
---
Internal Tracking ID: [EXPOSUREAPP-14268](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14268)
> Uninstall unneeded gulp plugins (gulp-load-plugins and gulp-uglify)

- cypress/support/e2e.js
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3200 "Bad formatting in Cypress soft assertions headless error messages"
It corrects the tab and new line formatting characters in [cypress/support/e2e.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/support/e2e.js) used in headless mode.
Temporarily edit `src/data/faq.json` and introduce several errors such as removing `target='_blank'` from two links.
In one terminal execute
`npm start`
Once the localhost website is shown in a browser open a second terminal and execute
`npx cypress run -s 'cypress/e2e/faq_link_attr.cy.js'`
Check that the error message looks correctly formatted with each error starting on a separate line such as:
```
1 failing
1) Check attributes of FAQ links
Check links …
```
> Correct Cypress message formatting for softAssert in headless mode

- README.md
As discovered in #3202, Rosetta is required to be installed in order to build this project on Apple Silicon Mac computers. With this PR, the requirements for development in the [README.md](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) have been extended accordingly. 
---
Internal Tracking ID: [EXPOSUREAPP-14298](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14298)
> Update README.md: Include Rosetta requirement

- README.md
This PR follows on from issue https://github.com/corona-warn-app/cwa-website/issues/3204 "Pruning Cypress cache to reclaim disk space".
It adds helpful information to the [README](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) file on how to reclaim storage space taken up by multiple cached Cypress versions.
Cypress automatically caches a copy of each version of Cypress at the time of installation. Updating to a later version of Cypress does not automatically clear out the Cypress cache, so over time it is possible that more and more storage space is taken up unnecessarily by cached Cypress versions.
The text added to the [README](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) file explains how to check for storage space used by Cypress cached …
> Add Cypress cache housekeeping instructions to README

- blog/2022-02-23-cwa-2-18/index.md
- blog/2022-02-23-cwa-2-18/index_de.md
This PR resolves an HTML-compliance issue in:
- https://www.coronawarn.app/en/blog/2022-02-23-cwa-2-18/ and
- https://www.coronawarn.app/de/blog/2022-02-23-cwa-2-18/
`px` is removed from `width` attributes in `img` tags. Pixel as unit is implied and must not be explicitly specified.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-width
"width
The intrinsic width of the image in pixels. Must be an integer without a unit."
> Fix img width attribute in 2.18 blog

- src/data/faq_de.json
This PR resolves the issue https://github.com/corona-warn-app/cwa-website/issues/3249 "Duplicated FAQ article #multiple_exposure_checks (DE)"
The out of date article #multiple_exposure_checks is deleted from the section https://www.coronawarn.app/de/faq/results/#risk_assessment "Technische Zusammen­hänge / Risiko-Ermittlung" where it is misplaced and missing the updated information.
Open https://www.coronawarn.app/de/faq/results/ and search for the term "zeitgleiche Einträge"
Only one article should appear and this should be in the section https://www.coronawarn.app/de/faq/results/#resolved "Support / Geklärt".
Open the article https://www.coronawarn.app/de/faq/results/#multiple_exposure_checks and check that it contains the text "AKTUELL
Seit Version 1.6.0 der Corona-Warn-App ..."
> Removed outdated and duplicated FAQ #multiple_exposure_checks (DE)

- src/partials/page-faq.html
This PR resolves the enhancement request https://github.com/corona-warn-app/cwa-website/issues/3246 "FAQ Sections is not centered".
The lower section of https://www.coronawarn.app/en/faq/ is now centered so that it has a consistent look independently of the available browser width.
---
Previously
---
Desktop wide
---
Desktop narrow
---
Mobile
> Center the FAQ lists

- src/layouts/blog.html
- src/layouts/default.html
- src/layouts/error-pages.html
- src/layouts/science.html
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3266 "main role (ARIA) not recommended."
The attribute declaration `role="main"` is removed from layout html files in [src/layouts](https://github.com/corona-warn-app/cwa-website/tree/master/src/layouts)
Run https://validator.w3.org/ on 
- https://www.coronawarn.app/en/ 
- https://www.coronawarn.app/en/blog/
- https://www.coronawarn.app/en/science/
https://www.coronawarn.app/en/faq/ and ensure that the following warning message does not appear:
"The main role is unnecessary for element main."
Also check:
- https://www.coronawarn.app/en/unknown
and select "Validate error pages" before clicking on "Check".
> Remove role="main" from layout files

- docs/WRITE_BLOG_POSTS.md
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3269 "Incorrect guidance in WRITE_BLOG_POSTS for images"
It updates the document WRITE_BLOG_POSTS.md.
1. The example is converted to use `class="text-center"` 
2. A link to the bootstrap documentation is added
3. The non-working code to show an image on GitHub is removed. The syntax for GitHub and the cwa-website are different, so it is not useful to attempt to display an image in the GitHub document.
To easily view the changed document when reviewing, open https://github.com/MikeMcC399/cwa-website/blob/fix/blog-post-doc-guide/docs/WRITE_BLOG_POSTS.md.
> Update WRITE_BLOG_POSTS.md for images

- .github/workflows/cypress-test-prod.yml
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3276 "Cypress production test runs with older Node.js 16 version" by removing the dependency of the workflow on the action [cypress-io/github-action@v4](https://github.com/cypress-io/github-action) and replacing it by a direct call of Cypress.
The Cypress call is preceded by a call to [actions/setup-node](https://github.com/actions/setup-node) to install the Node.js `lts/hydrogen` version 18.12.1 and by a call to `npm ci` to install npm dependencies, including Cypress. The environment variable `TERM: xterm` is added to prevent a spurious warning `tput: No value for $TERM and no -T specified` from Cypress running in headless mode.
Check the version of Node.js reported by Cypress is as follows:
"Node Version: …
> Cypress test remove dependency on cypress-io/github-action

- .github/workflows/cypress-test-prod.yml
- README.md
- cypress/e2e/mime.cy.js
This PR implements a workaround proposed in #3071.
When visiting FAQ articles with a non-legacy FAQ-URL in a Cypress test with the baseURL https://coronawarn.app, the second visit times out. If the URL is replaced with https://www.coronawarn.app, it doesn't time out. Steps to reproduce can be found in the aforementioned issue.
---
Internal Tracking ID: [EXPOSUREAPP-14103](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14103)
> Change Cypress baseURL to https://www.coronawarn.app

- src/data/faq.json
- src/data/faq_de.json
This PR adds two more paragraphs to the [#cause2001](http://localhost:8000/en/faq/results/#cause2001) FAQ article. The content was previously suggested in [this issue](https://github.com/corona-warn-app/cwa-website/issues/925). 
---
Internal Tracking ID: [EXPOSUREAPP-14426](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14426)
> Update FAQ #cause2001: Add hints to restart device & try with mobile data

- gulpfile.mjs
- src/data/faq.json
- src/data/faq_de.json
While going through the FAQ for another task, I came across the [#update_faq](https://www.coronawarn.app/en/faq/results/#update_faq) article and noticed something odd. Although we haven't merged any FAQ changes this year, it already showed a 2023 date. Instead of showing the date of the last FAQ change, it shows the date from when the site was built. Every merged PR or scheduled deployment would update that date, not just FAQ changes like intended. 
After thinking about fixing this, I came up with an alternative idea. In my opinion, it doesn't really make sense to specify this in the FAQ if it's always up to date anyway. Especially not if that is the only information included in the FAQ article, with no text whatsoever. Linking to the GitHub file history for …
> Update FAQ #update_faq: Link to GitHub file history

- README.md
- package-lock.json
- package.json
This PR implements one suggestion from https://github.com/corona-warn-app/cwa-website/issues/3308 "Improve testing for PR submission".
It provides a new script which can be run with:
`npm run test:short`
This runs all Cypress tests except [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js).
Execute
`npm run test:short`
and confirm that there are no errors reported.
---
Internal Tracking ID: [EXPOSUREAPP-14530](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14530)
> Add short Cypress test script npm run test:short

- docs/FAQ_SEARCH_SUMMARY.md
In [FAQ_SEARCH_SUMMARY.md](https://github.com/corona-warn-app/cwa-website/blob/master/docs/FAQ_SEARCH_SUMMARY.md), there is a link to the gulpfile. As it was renamed from gulpfile.js to gulpfile.mjs [here](https://github.com/corona-warn-app/cwa-website/pull/3181), the link to the gulpfile from there must have not worked ever since. With this PR, it now links to the gulpfile again.
> Update FAQ_SEARCH_SUMMARY: Invalid gulpfile link

- src/data/faq.json
- src/data/faq_de.json
This PR updates "Warn for others" FAQs in response to changes regarding TAN procedures in 3.0.
Dates will be inserted once approved or shortly before being merged. Apart from that, this PR is ready to be reviewed.
[Kann ich die Stellvertreter-Funktion nutzen, egal welchen QR-Code ich eingescannt habe?](https://www.coronawarn.app/de/faq/results/#check_in_luca_warn_for_others)
[Can I warn for others regardless of which QR code I have scanned?](https://www.coronawarn.app/en/faq/results/#check_in_luca_warn_for_others)
[Wie kann ich in Vertretung warnen?](https://www.coronawarn.app/de/faq/results/#warn_for_others)
[How can I warn for others?](https://www.coronawarn.app/en/faq/results/#warn_for_others)
---
Internal Tracking ID: [EXPOSUREAPP-14499](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP- …
> Release 3.0: Update FAQ articles mentioning "Warn for others"

- .github/workflows/build-and-test.yml
This PR implements the suggestion from issue https://github.com/corona-warn-app/cwa-website/issues/3308.
The workflow initially does not run automatically.
---
Internal Tracking ID: [EXPOSUREAPP-14535](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14535)
> Create build-and-test workflow

- .github/workflows/build-and-test.yml
This PR enables the PR trigger in the [build-and-test.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build-and-test.yml) workflow. 
The first manually triggered workflow ran successfully, as seen [here](https://github.com/corona-warn-app/cwa-website/actions/runs/3882434456/jobs/6622581219).
Once this PR is merged, the [build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) workflow will be disabled. In the next upcoming PR we should then only see this new workflow.
Thanks to @MikeMcC399 for initially providing this workflow and his extensive Cypress efforts in general. This will greatly improve the process of contributing to the project.
---
Internal Tracking ID: …
> Update build-and-test.yml: Enable PR trigger

- src/data/faq.json
- src/data/faq_de.json
This PR adds the "Warning without TAN" section to the FAQ for the version 3.0 release.
For simplicity, I've put them all into one screenshot for each language. I hope this is sufficient for reviewing. 
Anchors:
- Section: #warning_without_tan
- Articles (in correct order): 
#warn_without_tan,
#warn_without_tan_how_to,
#warn_without_tan_error,
#warn_without_tan_digital_result, 
#warn_without_tan_external_result,
#warn_without_tan_hotline,
#warn_without_tan_version,
#warn_without_tan_pcr_after_self_test,
#warn_without_tan_twice,
#warn_without_tan_still_positive,
#warn_without_tan_photo,
#warn_without_tan_how_often,
#warn_without_tan_family,
#warn_without_tan_event,
#warn_without_tan_quarantine,
#warn_without_tan_negative,
#warn_without_tan_contact_journal, …
> Release 3.0 | Update FAQ: Add "Warning without TAN" section

- src/data/global.json
This PR implements the suggestion from https://github.com/corona-warn-app/cwa-website/issues/3331 "References to TAN Hotline in footer" to add information about the shutdown of the TAN hotline on Jan 31, 2023 to the footer telephone numbers.
The shutdown date is added to the footer as a clickable link to the blog articles:
- [Version 3.0: CWA warnings now possible after positive self-test](https://www.coronawarn.app/en/blog/2023-01-18-cwa-3-0/) (EN)
- [Version 3.0: CWA-Warnungen jetzt auch nach positivem Selbsttest möglich](https://www.coronawarn.app/de/blog/2023-01-18-cwa-3-0/) (DE)
where more information is provided about the reasons for the shutdown and the fact that there will be a recorded message after the shutdown date.
This displays on the footer of a mobile device as follows:
| …
> Add TAN hotline shutdown date Jan 31, 2023 to web footer

- src/data/english-texts.json
This PR temporarily removes "Science" and "Science-Blog" from our accessibility automation that puts occurences in `<span>` tags. There will be a follow up PR that will fix the root cause of the problem and add "Science" and "Science-Blog" back to `english-texts.json` once we find a sufficient solution.
Example of the problem we're currently facing:
---
Internal Tracking ID: [EXPOSUREAPP-14701](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14701)
> Update english-texts.json | Remove "Science" and "Science-Blog"

- science/2021-06-15-science-blog-1/index.md
- science/2021-07-08-science-blog-2/index.md
- science/2021-08-02-science-blog-3/index.md
- science/2021-10-15-science-blog-4/index.md
- science/2022-03-03-science-blog-5/index.md
This PR updates the `update:` text in English science blogs containing information on when they were published and when their German counterparts were last edited. Thanks to @MikeMcC399 for the suggestion. For Science Blog 6, this has been done in https://github.com/corona-warn-app/cwa-website/pull/3363/commits/880c749b83a36aa3e8815fbb88a153aa158317f0.
---
Internal Tracking ID: [EXPOSUREAPP-14705)](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14705)
> Update science blogs: Improve update: text

- src/data/english-texts.json
- src/partials/button-back-component.html
PR #3368 introduced a temporary fix for the broken back-link rendering on Science-Blog Entries. 
This PR proposes a permanent fix for this problem. It adds the terms "Science" and "Science-Blog" again to the english-texts.json and wraps the complete text inside the link inside a span-tag to fix the rendering issue introduced by #3293.
Back Link after fix with english specifier:
---
Internal Tracking ID: [EXPOSUREAPP-14701](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14701)
> Permanent fix for broken back-link rendering on science-blog entries

- package-lock.json
- package.json
This PR updates
https://github.com/corona-warn-app/cwa-website/blob/0c52ddae35073311c9041c01aa04df5e88a13865/package.json#L85
to 1.15.4.
Execute
```bash
npm run open
```
and check that the logs show "HTTP status code 200" not "HTTP status code NaN" in the excerpt below:
```text
> start-server-and-test start-server http://localhost:8000 cypress:open
1: starting server using command "npm run start-server"
and when url "[ 'http://localhost:8000' ]" is responding with HTTP status code 200
running tests using command "npm run cypress:open"
```
Similarly to the above, examine the action log files in:
https://github.com/corona-warn-app/cwa-website/actions/workflows/build-and-test.yml
for the job `test`. It should show "HTTP status code 200".
> Solve issue url "[ 'http://localhost:8000' ]" is responding with HTTP status code NaN

- gulpfile.mjs
- src/data/analyse.json
This PR puts the dashboard fallback file to public/assets/dashboard instead of the public root directory.
---
Internal Tracking ID: [EXPOSUREAPP-14800](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14800)
> Update dashboard: Move fallback file

- cypress/e2e/hybrid/check_links.cy.js
This PR improves the reliability and performance of the Cypress test [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js).
The test [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js) has been failing with a browser out-of-memory crash when it was attempting to check blog entries. This started to occur after the introduction of additional links to blog articles placed near the topic of https://www.coronawarn.app/en/blog/ and https://www.coronawarn.app/de/blog/ (see issue https://github.com/corona-warn-app/cwa-website/issues/3391).
About 50 new links were added, which is about a 50% increase in the number of links on the blog …
> Check only main section for blog sub-entries

- science/2022-03-03-science-blog-5/index.md
- science/2022-03-03-science-blog-5/index_de.md
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3395 "Outdated link to App Store connect help in Science Blog 5"
It changes the link in
- https://www.coronawarn.app/en/science/2022-03-03-science-blog-5/#62-apple-app-store
- https://www.coronawarn.app/de/science/2022-03-03-science-blog-5/#62-apple-app-store
to the updated reference page https://developer.apple.com/help/app-store-connect/reference/app-metrics
Note: Trailing white space is also removed. To view the content changes without whitespace, select "Hide whitespace" in GitHub file diff options.
---
Internal Tracking ID: [EXPOSUREAPP-14808](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14808)
> Update link to apple app store metrics

- cypress/e2e/check_videos.cy.js
This PR implements the suggestion from https://github.com/corona-warn-app/cwa-website/issues/3397 "Cypress video check on directories without videos" to remove directories from the list to check in the [cypress/e2e/check_videos.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/check_videos.cy.js) test spec, where there are no videos located and there are none to be expected:
```text
'/de/eventregistration/',
'/en/eventregistration/',
'/de/community/',
'/en/community/',
'/de/analysis/',
'/en/analysis/',
'/de/blog/archiv/',
'/en/blog/archive/',
'/de/screenshots/',
'/en/screenshots/',
'/de/rat-partner/',
'/en/rat-partner/',
'/de/privacy/',
'/en/privacy/',
'/de/terms-of-use/',
'/en/terms-of-use/',
'/de/event-qr-code-guide/',
'/en/event-qr-code-guide/', …
```
> Remove unnecessary directories from video check

- cypress/e2e/hybrid/check_links.cy.js
This PR improves the Cypress test [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js) regarding maintaining the list of link targets which cannot be checked due to their network or security setup.
In the past there were two separate lists, one for the main check and one for the blog checks. The lists were complete URLs.
The motivation for this PR is to enable this Cypress test spec to be called successfully from a GitHub workflow. Some websites which allowed testing from a local environment cannot be automatically tested from GitHub, meaning that the list was getting longer and less manageable.
- The two lists are merged into one list.
- The list is now based on hostnames e.g. instead of the full URL …
> Improve check_links Cypress test to block hostnames not URLs

- .github/workflows/test-check_links.yml
This PR creates a workflow `.github/workflows/test-check_links.yml` which runs the Cypress test [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js) to check hyperlinks which are not anchors.
The test is run weekly every Monday at 03:15 UTC and on demand.
The workflow does not have a `pull_request` trigger because the success of the test relies in many cases on the correct performance of external third-party websites over which cwa-website has no control. Any failure needs to be followed up manually and should not result in a CI failure of any PR. Also the test takes much longer to run than any other of the Cypress tests. (Tests in a fork showed that it typically runs for approximately 18 minutes when …
> Workflow for check_links

- .github/workflows/test-checklinks-md.yml
This PR implements the suggestion from https://github.com/corona-warn-app/cwa-website/issues/3407 "Add a workflow to check Markdown links".
The workflow is triggered by a pull_request or manually and it executes the command
```bash
npm run checklinks
```
to check Markdown (*.md) files in the top level of cwa-website and in the `docs/` directory.
> Add workflow to check markdown links

- src/data/faq.json
- src/data/faq_de.json
This PR removes the link to the GitHub issue https://github.com/corona-warn-app/cwa-documentation/issues/569 from the FAQ entry `where_can_i_get_tested`.
- https://www.coronawarn.app/de/faq/results/#where_can_i_get_tested
- https://www.coronawarn.app/en/faq/results/#where_can_i_get_tested
**This PR needs normal review & approve process!**
---
Internal Tracking ID: [EXPOSUREAPP-14848](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14848)
> Remove GitHub issue link from FAQ entry `where_can_i_get_tested`

- package-lock.json
- package.json
This PR adds a new script `test:links` which runs the [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js) test locally.
This makes it easier for a contributor to check external links in the website to be published on https://www.coronawarn.app/ before submitting a PR or after making changes to it.
Other tests can already be run using `npm run test:short`. The full set of tests can be run using `npm test` (which is an alias for `npm run test`).
Due to the dependency of this test on external websites, which may or may not be working correctly when the test is run, and on the run time of approx. 15 - 25 minutes, the workflow check in [.github/workflows/test-check_links.yml](https://github.com/corona-warn-app/c …
> New script `test:links` for web hyperlink checking

- README.md
- docs/TESTING.md
This PR implements the suggestion from https://github.com/corona-warn-app/cwa-website/issues/3410.
Detailed testing information is moved from [README: Testing](https://github.com/corona-warn-app/cwa-website/blob/master/README.md#testing) into a new docs/TESTING.md file, which has re-worked contents that reflect the introduction of automatic testing. Some text from the original README which is no longer necessary has been removed.
Whilst this PR is open and not yet merged, the documents can be viewed under:
- [docs/testing-update/README.md](https://github.com/MikeMcC399/cwa-website/blob/docs/testing-update/README.md)
- [docs/TESTING.md](https://github.com/MikeMcC399/cwa-website/blob/docs/testing-update/docs/TESTING.md)
> Add TESTING document and simplify README

- cypress/e2e/hybrid/check_links.cy.js
- This PR addresses the issue reported in https://github.com/corona-warn-app/cwa-website/issues/3415#issuecomment-1455528374. It is an alternative resolution to PR https://github.com/corona-warn-app/cwa-website/pull/3417.
- It adds the hostname `buergertest.ecocare.center` to the list `noCheckHosts` in [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js), since https://buergertest.ecocare.center/#c734 responds with a 404 (Not Found) error.
```text
$ curl -I https://buergertest.ecocare.center/#c734
HTTP/2 404
x-ua-compatible: IE=edge
content-type: text/html; charset=utf-8
date: Tue, 07 Mar 2023 08:20:57 GMT
server: Apache
```
> Exclude buergertest.ecocare.center from link test

- cypress/e2e/hybrid/check_links.cy.js
- This PR addresses the link test failure in job [4401083360](https://github.com/corona-warn-app/cwa-website/actions/runs/4401083360)
"AssertionError: Link: https://corona-schnelltest-zentren.dm.de/o/dm/login: expected false to equal true"
arising from using the link in blog articles.
- It adds the hostname `corona-schnelltest-zentren.dm.de` to the list `noCheckHosts` in [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js), since https://corona-schnelltest-zentren.dm.de/o/dm/login responds with a 404 (Not Found) error.
```text
curl -I https://corona-schnelltest-zentren.dm.de/o/dm/login
HTTP/2 404
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
content-length: 19
date: Mon, 13 Mar …
```
> Exclude corona-schnelltest-zentren.dm.de from link test

- src/assets/scss/_faq.scss
- src/data/faq.json
- src/data/faq_de.json
Where an update text was available, there are now callouts for the updated FAQ entries
There are no callouts for entries, where there was no update text already provided, example:
There are also no callouts for texts that are structured like this: "Since version 2.5 [..], and since version 2.6" and contain a lot of text. As that would essentially make the whole entry a callout. Callouts are meant to highlight changes to the faq entry, not necessarily the app version.
(merging this soon already, but if there is feedback, please don't hesitate to write it into the already closed pr)
> Add callouts to FAQ entries for updates

- src/data/faq.json
- src/data/faq_de.json
As there are no textblocks in the recently added FAQ articles about the end of development of the Corona-Warn-App, `gulp-json-transform` prints a warning in the build process for each file (German and English). This can be seen [here](https://github.com/corona-warn-app/cwa-website/actions/runs/4466163815/jobs/7844002388#step:5:79).
```
gulp-json-transform: Cannot read properties of undefined (reading 'join')
```
To prevent this, this PR adds textblocks to the FAQ articles. As seen [here](https://github.com/corona-warn-app/cwa-website/actions/runs/4466163815/jobs/7844002388#step:5:79), this PR is working as intended.
---
Internal Tracking ID: [EXPOSUREAPP-14972](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14972)
> Update FAQ #end_of_development: Suppress warnings in build

- src/assets/js/analyse/chart.js
- src/assets/js/analyse/chart/update.js
- src/assets/js/analyse/index.js
- src/assets/scss/_analyse.scss
This PR adds an annotation to the dashboard to show when "Warning without TAN" was implemented into the app. This will help to understand why the statistics in the lower two tiles have significantly changed after this date.
---
Internal Tracking ID: [EXPOSUREAPP-14711](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14711)
> Update dashboard: Add annotations for Warning without TAN

- package-lock.json
- package.json
This PR fixes the warning message:
"Opening Cypress...
Couldn't find tsconfig.json. tsconfig-paths will be skipped"
which appears when using Cypress, for instance in the log files of https://github.com/corona-warn-app/cwa-website/actions/workflows/cypress-test-prod.yml
The error no longer occurs when [browser-sync](https://www.npmjs.com/package/browser-sync) is updated to `2.29.1` (latest), since this version removes the dependency on `"typescript": "^4.6.2"` (see https://github.com/BrowserSync/browser-sync/compare/v2.29.0...v2.29.1 where it persists in `devDependencies` only).
At the same time:
- [start-server-and-test](https://www.npmjs.com/package/start-server-and-test) is updated to `2.0.0` (latest)
- [cypress](https://www.npmjs.com/package/cypress) is updated to …
> Update testing dependencies

- src/assets/js/analyse/chart/update.js
As suggested by @MikeMcC399 [here](https://github.com/corona-warn-app/cwa-website/pull/3434#issuecomment-1479310170), we have added another annotation for the TestV changes into the 2nd, 3rd and 4th chart. 
---
Internal Tracking ID: [EXPOSUREAPP-14989](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14989)
> Update dashboard: Add TestV annotation

- src/data/blog.json
- src/services/blog-processor.js
This PR updates the blog overview on https://www.coronawarn.app/en/blog/ to show either "Read more" if there's more content in a blog than what's shown in the overview, or "To blog" if there is no more content after the overview. "Read more" would be misleading in the last case, as there is nothing more to be read. 
EN:
DE:
---
Internal Tracking ID: [EXPOSUREAPP-14990](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14990)
> Update blog: Add "Read more" button alternative

- src/assets/scss/_header.scss
- src/data/global.json
- src/partials/header.html
This PR adds a banner above the header that links to the explanatory FAQ entries about the end of development of the Corona-Warn-App.
Screenshots:
Desktop EN:
[coronawarn.app/en](https://user-images.githubusercontent.com/88365935/227459551-a7ae939e-da97-4103-98fb-24b3497d2998.png)
[coronawarn.app/en/faq](https://user-images.githubusercontent.com/88365935/227459560-b634ff95-119d-4595-8fe7-f7e1c9535736.png)
Desktop DE:
[coronawarn.app/de](https://user-images.githubusercontent.com/88365935/227459558-8805f04d-1167-4ede-b1f6-1caf222320a5.png)
[coronawarn.app/de/faq](https://user-images.githubusercontent.com/88365935/227459562-fc186656-ca5a-41b7-96f0-2d0d18b69abf.png)
Mobile EN:
[coronawarn.app/en](https://user-images.githubusercontent.com/88365935/227460091-791a1b73-59ca-4371-af91-877578784733. …
> Update header: Add end of development banner

- cypress/fixtures/appToWebLinks.json
[CCL v3.6.0](https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v3.6.0), which is now in productive use, adds `faqAnchor: ramp_down`.
This PR adds `#ramp_down` to the list of anchors for Cypress to test.
To be clearer where this came from
```
"cclVersionFirst": "3.5",
"cclVersionLast": "3.6",
```
is also added. This is pure commentary. It is not processed by any test.
> Add #ramp_down link check to Cypress tests

- src/data/faq.json
- src/data/faq_de.json
This PR removes the sentence: "Whether the CWA will still be available and/or downloadable on other platforms is not known by us and is the responsibility of the respective operators of these platforms or software distribution channels." or "Ob die CWA danach noch auf anderen Plattformen heruntergeladen werden kann, ist uns nicht bekannt und liegt in der Verantwortung der jeweiligen Plattform-Betreiber." from the [#ramp_down_stores](https://www.coronawarn.app/en/faq/results/#ramp_down_stores) FAQ entry
---
Internal Tracking ID: [EXPOSUREAPP-15000](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15000)
> Update FAQ #ramp_down_stores: Remove second sentence

- src/data/faq.json
- src/data/faq_de.json
This PR changes the English FAQ title of #ramp_down_apk to match with the German title by removing the word "still". In addition to that, the last sentence was slightly changed. See https://github.com/corona-warn-app/cwa-website/pull/3455#issuecomment-1490214683
> Update #ramp_down_apk: Small text and title changes

- src/data/faq.json
- src/data/faq_de.json
This PR corrects the definition of an Android APK, which is a single file containing all of the app code and which can be installed independently of access to the Google Play Store.
It resolves one aspect of issue #3449 and changes:
- https://www.coronawarn.app/en/faq/results/#ramp_down_apk
- https://www.coronawarn.app/de/faq/results/#ramp_down_apk
---
Internal Tracking ID: [EXPOSUREAPP-15017](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15017)
> fix: apk can be installed locally

- src/data/screenshots.json
Thanks to @MikeMcC399 for noticing this issue.
We decided on this standard format for English language dates a while ago. Also the month "Februar" is the German spelling, not the English spelling.
> Update Screenshots 3.1 | Fix date format

- src/data/faq.json
Simplification of English text for ENF deactivation.
This follows on from the suggestion in https://github.com/corona-warn-app/cwa-website/pull/3457#discussion_r1162449312.
The English text is better aligned to the German text and thereby also simplified.
https://www.coronawarn.app/en/faq/results/#ramp_down_info reads:
"After April 30, 2023, the Corona-Warn-App will deactivate the ENF (Exposure Notification Framework)."
> update ramp_down_info FAQ EN

- blog/2023-04-19-cwa-3-2/index.md
- blog/2023-04-19-cwa-3-2/index_de.md
This PR fixes an issue where the FAQ link inside the blog wouldn't link to the FAQ when clicking on it from the blog overview.
> Fix Blog 3.2 | Invalid link

- .github/workflows/build-and-test.yml
- .github/workflows/cypress-test-prod.yml
This is a workaround for issue https://github.com/corona-warn-app/cwa-website/issues/3479.
It disables the test [cypress/e2e/faq_link_attr.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/faq_link_attr.cy.js) from running in CI workflows.
Internal Tracking ID: [EXPOSUREAPP-15135](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15135)
> disable faq_link_attr test in CI

- src/data/screenshots.json
- src/data/screenshots_de.json
This PR adds an informational disclaimer to the screenshots page, stating that it shows the screenshots prior to function reduction on May 1.
- https://github.com/corona-warn-app/cwa-website/blob/master/src/data/screenshots.json
- https://github.com/corona-warn-app/cwa-website/blob/master/src/data/screenshots_de.json
| English | German |
|---|---|
| <img src="https://user-images.githubusercontent.com/67682506/235779972-55374d7d-5eee-4920-8cb7-43faff470ba9.png" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/235779996-2a14f74a-215a-4abb-9b2c-c908fb5ab077.png" width="300"> |
---
**Fixes https://github.com/corona-warn-app/cwa-website/issues/3481**
---
Internal Tracking ID: [EXPOSUREAPP-14634](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14634)
> Add information to screenshots page

- src/data/event-qr-code-guide.json
- src/data/event-qr-code-guide_de.json
- src/data/eventregistration.json
- src/data/eventregistration_de.json
- src/partials/page-event-qr-code-guide.html
- src/partials/page-eventregistration.html
See https://github.com/corona-warn-app/cwa-website/issues/3484
Blue info-box added to:
1. https://www.coronawarn.app/de/eventregistration/
2.  https://www.coronawarn.app/en/eventregistration/
3.  https://www.coronawarn.app/en/event-qr-code-guide/
4. https://www.coronawarn.app/de/event-qr-code-guide/
**- DE info box**
**- EN info box**
---
Internal Tracking ID: [EXPOSUREAPP-15169](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15169)
> Event QR Code pages: Explanation about outdated page info in blue box 

- src/data/faq.json
- src/data/faq_de.json
This PR changes the date of the app removal, as the app will continue to be available until mid-June, in the FAQ entry `ramp_down_stores`
| English | German |
|---|---|
| ![Bildschirmfoto 2023-05-31 um 15 04 03](https://github.com/corona-warn-app/cwa-website/assets/67682506/d0b5f22c-fd42-4209-ba9e-7b02cac7aef9) | ![Bildschirmfoto 2023-05-31 um 15 03 39](https://github.com/corona-warn-app/cwa-website/assets/67682506/f1928f02-e15b-4ff3-b04b-e571d6c6d3d2) |
> Change app removal date in FAQ entry `ramp_down_stores`

- science/2021-07-08-science-blog-2/index.md
- science/2021-07-08-science-blog-2/index_de.md
After review with the team we agreed that there needs to be a way to jump back to the text where the footnote is linked to. This PR implements this.
> Add link back to the footnote (SB 2)

- .github/workflows/build-and-test.yml
- docs/TESTING.md
- src/partials/page-index.html
- remove from documentation "testing.md":
| applink_spec       | Detects broken links or missing OS badges to download mobile app in home page.                                          |
- remove cypress test app link 
- Update page-index.html: remove last section on main page: "Download the app":
**OLD**
**NEW**
> Remove last section on main page: "Download the app"
