corona-warn-app/cwa-website

src/assets/scss/_accordion.scss
Fixes issue #5 
Before:
After:
=> Fix accordion body border glitch

src/data/faq_de.json
Fix typos, wrong grammar, missing words, broken formatting etc.
=> Fix typos in FAQ

src/partials/footer.html
Trivial fix in an if clause of the footer partial @SebastianWolf-SAP @tkowark
=> fix: corrected if clause

src/assets/scss/_box.scss
Corrected parameter value @SebastianWolf-SAP @tkowark
=> fix: mismatched scss parameter

src/data/faq.json, src/data/faq_de.json
- "Will encounters still be logged when I close the app?" / "Muss ich die App immer geöffnet lassen, damit Begegnungen aufgezeichnet werden?"
- "iOS: Will risk identification still work if I turn off Bluetooth in my Control Center while keeping it activated in the system settings?" / "iOS: Funktioniert die Risiko-Ermittlung noch, wenn ich Bluetooth im Kontrollzentrum abschalte, aber in den Systemeinstellungen aktiviert lasse?
=> FAQ DE/EN Two new questions

src/data/faq.json, src/data/faq_de.json
"Will the collected random IDs be included when I back up data on my phone?" / "Werden die gesammelten Zufallskennungen in meiner Smartphone-Datensicherung (Backup) berücksichtigt?"
=> New FAQ (DE+EN): backup of collected random IDs

src/assets/js/app.js
=> Unfold FAQ accordion on deeplink by default

src/data/community.json, src/data/community_de.json
Thank you @MichaelPFrey for spotting this inconsistencies. Pointers to the individual Contribution guidelines are now added with this PR.
=> Explicit pointer to contribution guidelines (closes #116)

.gitignore, package-lock.json
1. Removed package-lock.json from .gitignore
2. Created package-lock.json by running npm install
Fixes #27
=> Package lock fix

src/assets/js/static/redirect.js
Improves support for browsers that may request another language before German or English.
=> Use navigator.languages for redirect

gulpfile.js, package-lock.json, package.json, src/data/index.json, src/data/index_de.json, src/data/news.json, src/data/news_combined.json, src/partials/image-attributes.html, src/partials/image-component.html, src/partials/page-community.html, src/partials/page-index.html
To resolve #64 here is the PR:
- Add WebP generation into the Build-Support
- Add src-webp url when necessary
- Update the image-component to create a picture set with Fallback for Non-WebP supporting Browser (Safari)
=> Adding of WebP support with PNG/JPEG as Fallback

gulpfile.js, package-lock.json, package.json, src/data/index.json, src/data/index_de.json, src/data/news.json, src/data/news_combined.json, src/partials/image-attributes.html, src/partials/image-component.html, src/partials/page-community.html, src/partials/page-index.html
Reverts corona-warn-app/cwa-website#65 until I've figured out how to add libpng support
=> Revert "Adding of WebP support with PNG/JPEG as Fallback"

src/assets/scss/_footer.scss, src/partials/footer.html
I improved the style of the footer, because it was on some screens a little bit crappy.
Before:
After:
=> Improved appearance of footer

src/data/faq.json, src/data/faq_de.json
Reverts corona-warn-app/cwa-website#148
=> Add Common Issue FAQ Section

src/data/faq.json, src/data/faq_de.json
... and also expanded the availability questions by default.
=> Added 14 of 14 days FAQ

src/data/faq.json, src/data/faq_de.json
expand all q&a; label q&a with standard phrase [Apple/iOS] and [Google/Android]
=> FAQ (EN/DE): Improve visibility

src/data/faq.json, src/data/faq_de.json
backend_ops: present tense
non_dev_related: link to BReg website added
=> Update FAQ (EN/DE) : minor improvements

src/data/index.json, src/data/index_de.json, src/partials/footer.html, src/partials/navlist-item.html, src/partials/page-index.html, src/partials/section-get-app.html
I did some improvements to satisfy [Google's Lighthouse Accessability tests](https://web.dev/measure/).
_this also fixes #94 as far as I can see it._
Please let me know If you need me to change this PR in any way.
=> Accessibility Improvements

src/data/global.json, src/partials/footer.html
=> feat(footer): copyright link to contributors

src/assets/img/running-app.svg
This Merge Request was created to fix #195, but it also improves the image:
=> fix: replaced running-app.png with a svg image

src/assets/img/running-app.svg
fixes #199
Tests:
- :heavy_check_mark: Safari 13.1 (Mac Catalina)
- :heavy_check_mark: iPhone 11
- :heavy_check_mark: iPhone XS
- :heavy_check_mark: iPhone 8
=> fix(#199): svg-fix for safari

src/partials/global-nav.html
Summary of changes:
Accessibility - added ARIA label for navbar open button: "Open Page Navigation Menu"
Accessibility - added ARIA label for navbar close button: "Close Page Navigation Menu"
=> Added ARIA Labels to mobile navbar toggle buttons

src/data/faq.json
no change in meaning, no additional info
=> Improve word order of a few faqs

src/data/faq.json, src/data/faq_de.json
days_active_Android, days_active_explanation
notif_weekly_update moved behind multiple_exposure_checks
=> FAQs moved to Resolved section

src/data/faq.json, src/data/faq_de.json
move down: ENError11, ENError13, iphone_region_change, memory, cause_3
move up: encounter_but_green, android_location
=> move FAQ according to criticality

src/assets/js/app.js
doing to lowercase in search method, so we're independent of the caller.
=> Fixed casing for search

src/data/faq_de.json
Added a paragraph with the recommendation to reset the app data instead of reinstalling the app in case of issues
=> Update Delete Random IDs

src/data/faq.json
Added a paragraph about resetting app data before you reinstall the app.
Please check the formatting, not sure if it's correct.
=> Update faq.json: delete_random_ids

cypress/integration/blog_spec.js, src/services/blog-processor.js
It seems some nth-child selectors are unstable. This is fixed in this PR.
=> Stabilize e2e selector

cypress/integration/blog_spec.js
This tests seems to have random false negatives and often blocks the entire build
=> Disable visual comparison test

blog/2020-08-25-notes-qr-codes/index.md, blog/2020-08-25-notes-qr-codes/index_de.md
There was an update on the number of Downloads of the App, which we had to change.
=> qr-code-notes_updated numbers in english and german version

blog/2020-08-11-hinweise-qr-code/index.md, blog/2020-08-11-hinweise-qr-code/index_de.md, config.yml, gulpfile.js, src/assets/js/static/faq-redirect.js, src/assets/js/static/page-redirect.js, src/pages/de/faq/(17).html, src/pages/de/faq/(39508).html, src/pages/de/faq/(9002).html, src/pages/en/faq/(17).html, src/pages/en/faq/(39508).html, src/pages/en/faq/(9002).html, src/partials/faq-redirect.html, src/partials/page-redirect.html, src/services/blog-processor.js
If an old blog entry is replaced with a new one, the old link might be available somewhere.
This PR introduces the possibility to still use the old link but get redirected to the replacement entry.
=> Allow Redirection from Old Blog Entries

src/data/faq.json, src/data/faq_de.json
qr_test: editorial
status_14: editorial
simple german: change to Risiko-Begegnung, Risiko-Ermittlung
Hyphentation: Robert Koch-Institut
=> Editorial updates, eg for qr_test, status_14

src/assets/js/app.js
I added an scrolling animation when clicking an anchor link.
=> Added smooth scrolling to anchor tag when clicking anchor link

src/data/faq.json, src/data/faq_de.json
low_risk_text
app_does_not_open
iOS_136
when_ready
keys0
fixed typo (2x): Hintergrundaktivät
=> Move resolved FAQ to Resolved

gulpfile.js, src/assets/js/app.js
Reverts corona-warn-app/cwa-website#328
Emergency revert since the Mime-Type Change breaks the JSON download.
=> Revert "The FAQ search JS code should not care about the language"

gulpfile.js, src/assets/js/app.js
Reverts corona-warn-app/cwa-website#329
this time with explicit converting of the response to JSON.
=> The FAQ search JS code should not care about the language

src/data/blog.json, src/data/global.json, src/data/index.json, src/data/index_de.json, src/pages/de/blog/index.html, src/pages/en/blog/index.html, src/pages/en/community/index.html, src/partials/footer.html, src/partials/icon-list-component.html, src/partials/image-component.html, src/partials/page-blog-index.html, src/partials/page-faq.html, src/partials/page-index.html, src/partials/text-component.html
This rather big PR introduces many small optimizations geared towards search engines.
* Added more speaking alt tags to images
* Improved page structure of FAQs
* Improved linking to FAQ page from other parts of the page
* Better Meta tags for certain pages
* Fixed some issues introduced by non-suitable partials (icon-list-component)
=> Search Engine Optimization

src/data/faq.json, src/data/faq_de.json
Closes https://github.com/corona-warn-app/cwa-website/issues/351
=> added faq entry for ene

.github/workflows/deploy-master.yml
…bssl are not harmonizing as of error
Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0-dev_1.0.2n-1ubuntu5.3_amd64.deb  404  Not Found [IP: 52.168.50.79 80]
=> Fixed production build

src/data/global.json, src/pages/de/index.html, src/pages/en/index.html, src/partials/header.html, src/partials/page-index.html
Add Header "Wer hilft bei Fragen zur Corona-Warn-App?"
=> Add Header "Wer hilft bei Fragen zur Corona-Warn-App?"

src/data/index.json, src/data/index_de.json
Please **DON'T** merge until 1.3.2/1.3.1 are finally in the App Store/Google Play Store!
=> Update Versions on the Main Page

src/data/faq.json, src/data/faq_de.json
=> Updated FAQ entry according to updated information from #388

src/data/faq.json, src/data/faq_de.json
closes https://github.com/corona-warn-app/cwa-website/issues/431
closes https://github.com/corona-warn-app/cwa-app-android/pull/846
=> added faq entries for rooted_devices

src/data/faq.json, src/data/faq_de.json
closes https://github.com/corona-warn-app/cwa-website/issues/430
=> updated faq entry for mobile_data_costs

src/data/faq.json, src/data/faq_de.json
closes https://github.com/corona-warn-app/cwa-website/issues/426
closes https://github.com/corona-warn-app/cwa-app-ios/issues/1193
=> added faq entry for ios_black_screen

src/data/faq.json, src/data/faq_de.json
Closing #425 
Please note that the FAQ entry is still under "Solved", I wasn't sure how I should lift it up to the "Common Issues" Section...
@svengabr If you are happy with these changes please approve and merge them. Thanks.
=> Update FAQ error 11

src/data/faq.json, src/data/faq_de.json
closes https://github.com/corona-warn-app/cwa-website/issues/439
=> added link to existing github issue

src/assets/js/app.js
closes https://github.com/corona-warn-app/cwa-website/issues/440
=> disabled scrollTop to prevent critical bug after using the search

src/data/faq.json, src/data/faq_de.json
Closes #449 
FAQ Update prepared for the release 1.5
=> FAQ - update age restriction info for stores

src/data/faq_de.json
Closes #448 
FAQ Update prepared for the release 1.5
=> FAQ - Change mention of 'Zufallscodes' to 'Zufalls-IDs'.

src/data/faq.json, src/data/faq_de.json
closes https://github.com/corona-warn-app/cwa-website/issues/422
=> changed faq text for keys_matches

src/data/faq.json, src/data/faq_de.json
=> FAQ - Add entry for interoperability gateways

src/assets/scss/_tables.scss, src/assets/scss/style.scss
added styles for new interop table
=> added table styles

src/data/faq.json, src/data/faq_de.json
* updated 39508 faq text with a note to wait up to 2 hours
=> updated 39508 faq text

blog/2020-10-19-version-1-5/index.md, blog/2020-10-19-version-1-5/index_de.md
Fixes https://github.com/corona-warn-app/cwa-website/issues/482#issuecomment-714583038
=> FAQ - Merge instructions for viewing Transnational Exposure Logging on Android and iOS

src/data/faq.json, src/data/faq_de.json
=> FAQ - Address change of minimum iOS version requirement

src/data/faq.json, src/data/faq_de.json
Fixes https://github.com/corona-warn-app/cwa-website/issues/454
=> FAQ - Move entry for 'iOS weekly update' to resolved category

src/data/faq.json
=> fixed typo

src/data/faq.json, src/data/faq_de.json
Fixes https://github.com/corona-warn-app/cwa-website/issues/528.
=> FAQ - Handling positive test results with 2 smartphones

src/data/faq.json, src/data/faq_de.json
=> FAQ - Clarify that CWA works in iOS power saving mode

src/data/faq.json, src/data/faq_de.json
Fixes #578 
Moves the entry to the **Solved** section.
=> FAQ - Update on multiple exposure checks

src/data/faq.json, src/data/faq_de.json
=> FAQ - Move 'Risk Assessment' category under 'Use'

src/data/faq.json, src/data/faq_de.json
Closes https://github.com/corona-warn-app/cwa-website/issues/665
=> faq-min-requirements-ios-12-5

src/data/faq.json, src/data/faq_de.json
=> ENError: only display error message for respective FAQ language

src/data/faq.json
Fixes https://github.com/corona-warn-app/cwa-website/issues/726
=> FAQ - fix ENError 13 english error message

src/data/faq.json, src/data/faq_de.json
=> FAQ entry - Virus variations / mutations

src/data/faq.json, src/data/faq_de.json
Closes https://github.com/corona-warn-app/cwa-website/issues/784
=> FAQ Contact diary

src/data/faq_de.json
https://github.com/corona-warn-app/cwa-website/pull/792#issuecomment-761613843
=> FAQ 2001 - correct grammar. 

src/data/faq.json, src/data/faq_de.json
Reslves https://github.com/corona-warn-app/cwa-website/issues/798
=> FAQ - Rapid tests / Schnelltests

src/data/faq_de.json
This PR adds a comma and changes das -> dass in the FAQ entry „update_iOS“ (DE only)
=> Add comma and change das -> dass („update_iOS“)

src/data/community_de.json
This PR aligns (corrects a link) in the German to the English text in "community_de".
=> Fix a link in "community_de"

gulpfile.js
=> Update current app version (1.14.0 -> 1.14.3)

src/data/faq.json, src/data/faq_de.json
Update FAQ:
---
https://www.coronawarn.app/de/faq/#recovered 
https://www.coronawarn.app/en/faq/#recovered
NEW TEXT
---
**DE**
Seit der Version 1.13 haben Sie die Möglichkeit nach einer überstanden SARS-CoV-2 Infektion, die App wieder zu aktivieren und die Fortführung der Risiko-Ermittlung nach Teilung der eigenen Zufalls-IDs erneut zu starten. Dies bedeutet, dass Sie nun entscheiden können, ob und wann Sie die Risiko-Ermittlung wieder einschalten, nachdem Sie Ihre verschlüsselten Zufalls-IDs nach einem Positivtest geteilt und andere damit gewarnt haben. Bisher war dies nur über ein Reset der App möglich.
**EN**
Since version 1.13, you have the option to reactivate the app after recovering from a SARS-CoV-2 infection and to restart the risk assessment after sharing your own random IDs. …
=> FAQ - update "recovered"

src/data/faq.json, src/data/faq_de.json
I made a mistake with the links to the blog in #1012.
This PR fixes the issue.
=> Fix broken links to blog in "mutation"

src/data/screenshots.json, src/data/screenshots_de.json
fixed a case sensitive bug for new android check in screenshots
=> Release screenshots

src/assets/js/eventregistration.js, src/data/eventregistration.json, src/data/eventregistration_de.json, src/partials/page-eventregistration.html
* Location type is no longer pre-filled
* Added error message for empty location type
=> added location type placeholder and error message

src/data/faq.json
=> FAQ google_security_vulnerability

src/data/eventregistration.json, src/data/eventregistration_de.json, src/partials/page-eventregistration.html
=> added section headers for event dropdown

src/data/faq.json, src/data/faq_de.json
This PR removes accidentally added empty lines from the FAQ.
=> Remove empty lines from FAQ

src/assets/js/eventregistration.js, src/data/eventregistration.json, src/data/eventregistration_de.json, src/partials/page-eventregistration.html
This PR resolves #1145.
Disabling logic and button position for the new print button are already implemented as in #1196.
=> add print button to eventregistration

src/data/faq.json, src/data/faq_de.json
This PR moves the entry "rapid_test" to the solved section and updates it with the information that it's now possible to enter RAT into the app.
<details>
<summary>Preview of the changes</summary>
| German | English |
| --- | --- |
| ![German](https://user-images.githubusercontent.com/67682506/117537949-4477ed00-b004-11eb-8651-07e891868db5.png) | ![English](https://user-images.githubusercontent.com/67682506/117537973-5b1e4400-b004-11eb-998b-611eb81de48b.png) |
</details>
---
Closes #1195
=>  Move "rapid_test" to solved section (Closes #1195)

src/data/global.json, src/data/index.json, src/data/index_de.json
@dsarkar I found a few more missing '-' in Tooltips of pictures.
=> add '-' to Corona-Warn App in Tooltips

src/data/faq.json, src/data/faq_de.json
vaccination_certificate_multiple_scan_possible
=> FAQ vaccination_certificate_multiple_scan_possible

src/data/faq.json, src/data/faq_de.json
Fixed a few typos:
-  ausserdem -> außerdem
- consistent usage of "Impfausweis" instead of sometimes Impfausweis and sometimes Impfpass
- whitespaces
- ich ...habe instead of ich ... haben
- einscannen instead of abscannen
=> faq vaccination: some fixes

src/data/faq.json, src/data/faq_de.json
Resolves https://github.com/corona-warn-app/cwa-website/issues/1287
=> FAQ - Add small entry explaining the staged rollout

src/data/faq.json, src/data/faq_de.json
Fixes: https://github.com/corona-warn-app/cwa-website/issues/1349
=> Fix upside down image

src/data/global.json
fixed a broken link on the screenshots archive dropdown
=> fixed broken link

src/data/faq.json, src/data/faq_de.json
DE version.
EN will follow separately
=> FAQ Test certificate 

src/data/global.json, src/partials/header.html, src/partials/page-index.html
Internal Tracking ID: [EXPOSUREAPP-8313](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8313)
=> Link to test portal

src/data/faq.json, src/data/faq_de.json
Fixes https://github.com/corona-warn-app/cwa-website/issues/1546
=> fix cert_eu_travel

src/data/faq.json, src/data/faq_de.json
---
Internal Tracking ID: [EXPOSUREAPP-8069](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8069)
=> Add FAQ article vac_cert_mismatch

src/data/faq.json, src/data/faq_de.json
This FAQ article was originally planned to only cover a guide on how to remove vaccination certificates, but was now generalized to cover any certificate removal
=> Add FAQ article eu_dcc_remove

src/data/faq.json, src/data/faq_de.json
As a response to [this issue](https://github.com/corona-warn-app/cwa-website/issues/1594), here's the pull request to add the discussed FAQ article.
German:
English:
=> Add FAQ article hc_signature_invalid 

src/data/eventregistration.json, src/data/eventregistration_de.json
This PR removes duplicate text from "introCLI".
=> Remove duplicate text from QR code generator page (EN)

src/data/screenshots-archive-2-5.json, src/data/screenshots-archive-2-5_de.json, src/data/screenshots-archive-2-6.json, src/data/screenshots-archive-2-6_de.json, src/data/screenshots.json, src/data/screenshots_de.json
This PR attempts to fix #1637 by updating and correcting the texts mentioned in #1637.
---
**Closes #1637**
=> Update screenshots information texts (Fixes #1637)

src/data/screenshots.json
Thanks for the [hint](https://github.com/corona-warn-app/cwa-website/pull/1663#issuecomment-905304132) @MikeMcC399
=> Correct spelling for 2.8 screenshots info text

src/partials/page-faq.html
Fixes https://github.com/corona-warn-app/cwa-website/issues/1673#issuecomment-907318956
=> fix glossary_links

src/data/faq.json, src/data/faq_de.json
Fixes https://github.com/corona-warn-app/cwa-website/issues/1693
---
Internal Tracking ID: [EXPOSUREAPP-9266](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9266)
=> Update FAQ vac_cert_red_warning

src/data/faq.json, src/data/faq_de.json
Fixes https://github.com/corona-warn-app/cwa-website/issues/1720
---
Internal Tracking ID: [EXPOSUREAPP-9229](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9229)
=> Update FAQ vac_cert_mismatch

src/data/global.json, src/data/screenshots-archive-2-8.json, src/data/screenshots-archive-2-8_de.json
Fixes issue https://github.com/corona-warn-app/cwa-website/issues/1722
=> fix sceenshots 2-8 site

src/data/global.json
=> Change order in menu: flip blog and science

src/data/faq.json, src/data/faq_de.json
This PR solves the issue [Request to add PPA (Privacy Preserving Analytics) to Glossary #1843](https://github.com/corona-warn-app/cwa-website/issues/1843) and adds the mentioned term to the glossary.
EN:
DE:
=> Add glossary entry "PPA"

src/pages/en/screenshots-archive/2-9.html, src/partials/global-nav.html
Now you can switch the language in other versions in the screenshot page
=> Fixed Language Switch in Screenshots

src/data/faq.json, src/data/faq_de.json
This pull request solves [New FAQ R2.12 #root_detection_android #1914
](https://github.com/corona-warn-app/cwa-website/issues/1914)
EN:
DE:
=> Add faq article root_detection_android

src/services/science-blog-processor.js
PR to fix issue cause of #1925. Removed hard-coded 'on' on date line.
=> Fix science blog date

blog/2021-11-03-cwa-2-13/index.md
=> Update blog: Replace 'Trash' with 'Recycle Bin'

src/data/faq.json, src/data/faq_de.json
Internal Tracking ID: [EXPOSUREBACK-1782](https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-1782)
=> FAQ vac_cert_invalid_211111

src/assets/scss/_science.scss, src/data/science.json, src/layouts/science.html
In this PR I had added a message just for mobile device users about figs situation on science blog page. Here are some screenshots:
=> Add message about statics figs for mobile devices

src/data/faq.json
This PR fixes an anchor in "vac_cert_booster" so that it works again.
Follow up to #2025.
Sorry for not spotting this in the PR before!
=> Fix anchor in "vac_cert_booster" 

src/assets/js/analyse/switch.js, src/assets/scss/_analyse.scss
Due to issue #2029 I added an event listener that changes the width of the background of the selected button from the menu every time the window is being resized.
=> Fix analysis background button

src/data/faq_de.json
This pr changes the small cased "codes" to "Codes" to be consistent.
=> faq_de: "QR-codes" -> "QR-Codes" (Capitalise "codes")

src/data/faq.json, src/data/faq_de.json
Due to issue #2093, I added these two entries to the FAQ section.
=> FAQ: scan_tips

.github/workflows/deploy-master.yml
In this PR, I have scheduled a restart every 12 hours to update analyseData.json
=> Schedule restart every 12 hours

.github/workflows/deploy-master.yml
In this PR, I have adapted the time of the scheduled restart to GMT time zone.
=> Update scheduled restart to GMT time

gulpfile.js
Quick fix for fix error on build
=> Catch error on create public folder on gulpfile

README.md
This PR changes "tests" to "Tests" in the README.md.
=> "Tests" with a capital "T" in README.md

src/data/faq_de.json
=> Fix white space - Update faq_de.json

src/data/faq.json, src/data/faq_de.json
Replaced "TSI" with "Deutsche Telekom" and changed the link to the pull requests regarding log4j.
=> Made further adjustments to the log4j faq article

src/data/faq.json, src/data/faq_de.json
- changed & added some text in the log4j-faq
=> added log4j-faq text

src/assets/js/analyse/chart/options.js
**Old Charts:**
**New Charts:**
=> fixed decimals in analysis

src/data/faq.json, src/data/faq_de.json
- Made Links prettier
- Text adjustments
- Fixed Search String
Suggestions by @MikeMcC399 & @Ein-Tim 
**OLD:**
**NEW:**
=> Log4j FAQ link, text and search string adjustments

blog/2021-12-20-cwa-2-15/index.md, blog/2021-12-20-cwa-2-15/index_de.md
Fixes https://github.com/corona-warn-app/cwa-website/issues/2216
=> Blog 2-15: add time stamp 0800

src/data/analyse_de.json, src/data/analyse_en.json
Fixes https://github.com/corona-warn-app/cwa-website/pull/2292#issuecomment-1007507004
=> Analysis page: Fix titles in graphs

blog/2022-01-11-omikron/index.md, blog/2022-01-11-omikron/index_de.md
This PR improves the blog post [2022-01-11-omikron"](https://www.coronawarn.app/de/blog/2022-01-11-cwa-omikron/) by:
- adding  `&nbsp;` in `z.B.`?
- changing a plain text link at the end of the blog
---
**Closes #2308**
=> Improve `2022-01-11-omikron` (Addresses #2308)

cypress/fixtures/copy/stringEn.json
Fix Cypress failure in Event Registration test caused by PR https://github.com/corona-warn-app/cwa-website/pull/2317.
=> Fix Cypress test, change from diary to journal

src/assets/js/analyse/expand.js
Due to issue #2321 I have created this PR. The problem was that the height was hard coded, it wasn't dynamic. Now it is.
=> Fix expand functionality

src/assets/js/analyse/expand.js
This PR revert changes made in https://github.com/corona-warn-app/cwa-website/pull/2323 to check if this change breaks display in vertical screens.
=> Revert fix expand functionality

src/assets/js/app.js
Now the button set always true or false, not the opposite.
=> Update expand/collapse functionality

src/assets/js/analyse/expand.js
This PR is to fix graph display on vertical screens
=> Fix graph in vertical screens

blog/2022-01-17-cwa-2-16/index_de.md
=> fix typo: daraufhin

src/data/faq_de.json
=> Update FAQ rat_how_long_valid: Fix typo

src/data/faq.json, src/data/faq_de.json
=> Fix/FAQ vc_2of1

src/data/faq.json, src/data/faq_de.json
Removed one sentence from FAQ based on the discussion in EXPOSUREAPP-11721
=> removal of sentence based on jira ticket EXPOSUREAPP-11721

src/assets/js/eventregistration.js
Focus is now set to the first error field on button press and validation logic regarding invalid dates is fixed to display the correct error message for every error case.
=> Event-Registration: Error field focus and validation logic fix

src/partials/page-eventregistration.html
Error messages are now displayed above the input-fields inside the label-tag
=> Event-Registration: Changed error-message placement

src/data/event-qr-code-guide.json, src/data/event-qr-code-guide_de.json
- Added text version of screenshots in the event-qr-code-guide page for accessibility.
**DE:**
**EN:**
=> event-qr-code-guide page accessibility improvements

src/data/analyse_de.json, src/data/analyse_en.json, src/partials/page-analyse.html
---
Internal Tracking ID: [EXPOSUREAPP-11980](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11980)
=> Add date format to label

src/assets/js/app.js
Internal Tracking ID: [EXPOSUREAPP-11979](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11979)
=> Remove app download sticky hiding when scrolling

science/2022-03-03-science-blog-5/index_de.md
Fixes
- https://github.com/corona-warn-app/cwa-website/pull/2497#discussion_r818455130
- Math images are now smaller
- Tables now need to be expanded to view them
=> Update tables and math

science/2022-03-03-science-blog-5/index_de.md
This PR completes an incomplete sentence.
- https://www.coronawarn.app/de/science/2022-03-03-science-blog-5/
This is a minor change, no screenshot required.
=> Add missing information to science blog 5

blog/2021-12-15-handlungsempfehlung-rote-kachel/index_de.md, blog/2022-01-21-cwa-uhrzeit-rote-kachel/index_de.md, blog/2022-02-23-cwa-2-18/index_de.md, science/2021-06-15-science-blog-1/index_de.md, science/2021-07-08-science-blog-2/index_de.md, science/2021-08-02-science-blog-3/index_de.md, science/2021-10-15-science-blog-4/index_de.md, science/2022-03-03-science-blog-5/index_de.md
Fixes
- https://github.com/corona-warn-app/cwa-website/pull/2497#discussion_r819390763
Additionally, this PR changes the German authors for all (science) blogs from "CWA Team" to "CWA-Team"
---
Internal Tracking ID: [EXPOSUREAPP-12117](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12117)
=> Update (science) blogs: New text and corrected authors

src/data/science.json
=> Remove italic effect from science blog text

src/data/faq.json, src/data/faq_de.json
---
Internal Tracking ID: [EXPOSUREAPP-12118](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12118)
=> Update FAQ 2.19 #rat_tan_hotline: Mention rapid PCR tests

src/data/faq.json, src/data/faq_de.json
---
Internal Tracking ID: [EXPOSUREAPP-12153](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12153)
=> Add FAQ: fault_tolerant_name_handling

src/assets/scss/_nav.scss
=> Remove box in accessibility statement

src/data/screenshots.json, src/data/screenshots_de.json, src/partials/page-screenshots.html
Added EN & DE descriptions for screenshots.
=> Screenshot descriptions

src/data/faq.json, src/data/faq_de.json
EN
DE
---
Internal Tracking ID: [EXPOSUREAPP-12442](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12442)
=> R 2.20 FAQ update #rec_cert

src/assets/scss/_accordion.scss
Due to issue #2579 I changed accordion-faq-body's max-height from 9000px to max-content
---
Internal Tracking ID: [EXPOSUREAPP-12445](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12445)
=> Increase faq-body max-height

src/data/faq.json, src/data/faq_de.json, src/data/faq_redirects.json
---
Internal Tracking ID: [EXPOSUREAPP-12446](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12446)
=> Fix section links 

src/data/faq.json, src/data/faq_de.json
---
Internal Tracking ID: [EXPOSUREAPP-12446](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12446)
=> technical_correlations_risk_assessment --> risk_assessment

src/data/faq.json, src/data/faq_de.json
Internal Tracking ID: [EXPOSUREAPP-12290](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12290)
=> R 2.20 update faq risk update 24

src/assets/js/app.js, src/partials/page-faq-results.html
=> count glossary results and show in left hand menu

blog/2022-03-30-cwa-2-20/index.md, blog/2022-03-30-cwa-2-20/index_de.md
Fixed the broken layout on the new blog entry:
=> layout fixes for new blog entry

blog/2022-03-30-cwa-2-20/index.md
=> Fixed typo in english version of newly released 2.20 blog post

src/assets/js/app.js
This PR fix issue #2584, the problem was that the mobile version did not simulate the click on the question, so it did not open it.
Here is a sample video:
https://user-images.githubusercontent.com/44208107/161026222-b8f3a153-e017-49c5-bafe-abfc775b9dd8.mp4
=> Fix expand FAQ container on visit URL with anchor

src/assets/scss/_custom-variables.scss
Changed background gradient to meet contrast requirements affecting the header, footer and some design elements in the middle of the web page.
My used colors were approved by the UX team.
Before
After
=> changed background gradient to meet contrast requirements

src/assets/scss/_faq.scss, src/data/faq.json, src/data/faq_de.json, src/partials/page-faq-results.html
Fix for Issue #2604
Changed the FAQ menu hint for small devices.
=> FAQ menu hint changed

src/data/faq.json
Reconciled Solution_architecture links in encounter_19_calc between en and de FAQ. Suggested by comment https://github.com/corona-warn-app/cwa-website/issues/2120#issuecomment-1084289821
=> encounter_19_calc link reconciliation

src/assets/js/app.js, src/partials/page-faq-results.html
I fix aria-selected issues with not alternate true and false properly
=> Fix glossary nav letters in FAQ's result page

src/data/faq.json, src/data/faq_de.json
=> Fix broken list & release version for Ukraine

src/data/index.json, src/data/index_de.json, src/partials/page-index.html
---
Internal Tracking ID: [EXPOSUREAPP-](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-)
=> Remove RAT partner button from main page

src/data/faq.json, src/data/faq_de.json
Internal Tracking ID: [EXPOSUREAPP-12622](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12622)
=> Add FAQ: #dcc_ri_429

src/assets/js/analyse/expand.js
Due to issue #2499 I fix screen position when clicked on dashboard charts's fullscreen buttons
=> Fix fullscreen button on dashboard charts

cypress/integration/blog_spec.js
Due to this issue #2714 I have fixed the issue related to the allow Cypress test suite.
=> Fix errors Cypress test suite

src/data/community.json, src/data/community_de.json, src/data/global.json
=> Fix broken anchor links

src/assets/js/app.js
I fix the redirects problems in FAQ page.
=> Fix redirects FAQ page

src/assets/js/app.js
I fixed a problem with FAQ's page on mobile. When you searched something and then click on the aside the page didn't work.
Here is a video where you can see the problem:
https://user-images.githubusercontent.com/56647466/164217854-701c2fc3-9add-43d0-a7ba-2cca387897c4.mp4
And here is a video with the problem fixed:
https://user-images.githubusercontent.com/56647466/164218569-983b5501-b915-469f-8ed5-6321a5324a65.mp4
=> Fix aside when have a search on mobile

src/assets/js/app.js
=> Fix issue on click FAQ to reset a search

src/partials/page-faq.html
This PR is to give a possible fix to #2747
=> Adapt col width depend of the breakpoint in FAQ home

src/data/index.json, src/data/index_de.json
Fixes #2559 
---
Internal Tracking ID: [EXPOSUREAPP-12902](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12902)
=> Edit Data Privacy and Safety text

src/data/faq.json, src/data/faq_de.json
=> Mention family rapid test profiles in glossary

src/data/faq.json, src/data/faq_de.json
=> Add FAQ #vac_status

src/assets/js/app.js
=> Remove function modifying results subheader links

science/2021-07-08-science-blog-2/index.md, science/2021-07-08-science-blog-2/index_de.md
This PR is for fixing a hidden figure in science blog 2
Before
After
=> Fix fig 5.1 in science blog 2

src/assets/js/science/htmlwidgets.js
This PR is for fix a small issue with the path of the JSON file from fig 6 at science blog 2
=> Fix figure 6 in science blog 2 in live CWA

.github/workflows/cypress-test-prod.yml
This PR adds the environment variable NO_COLOR to the workflow script `cypress-prod-test.yml` according to https://docs.cypress.io/guides/continuous-integration/introduction#Colors to suppress ANSI color output in Cypress logs.
Without setting NO_COLOR to true, the raw log output contains entries such as the following:
```
0m─[39m[90m─[39m[90m─[39m[90m┐[39m
2022-06-02T10:16:13.2926281Z [90m  │[39m [90mCypress:[39m        9.6.1                                                                          [90m│[39m
```
After setting the environment variable to true, the raw log output becomes readable instead:
```
2022-06-02T16:55:13.3589734Z   (Run Starting)
2022-06-02T16:55:13.3590111Z 
2022-06-02T16:55:13.3668095Z   ┌──────────────────────────────────────────────────────────────── …
```
=> Add NO_COLOR for Cypress

src/data/faq.json, src/data/faq_de.json
[#vac_status](https://www.coronawarn.app/en/faq/results/#vac_status)
[#vac_status](https://www.coronawarn.app/de/faq/results/#vac_status)
---
Internal Tracking ID: [EXPOSUREAPP-13621](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13621)
=> Update FAQ #vac_status: Add link to STIKO

science/2022-03-03-science-blog-5/index_de.md
This PR fixes a typo in the Table of Contents of https://www.coronawarn.app/de/science/2022-03-03-science-blog-5/
The ToC is made to agree with the contents heading:
"2 Die CWA erfüllt ihren Zweck und ist wirksam"
=> Fix typo in Science 5 Table of Contents (DE)

blog/2022-07-27-cwa-2-25/index.md, blog/2022-07-27-cwa-2-25/index_de.md
@MikeMcC399 thanks for the quick information in https://github.com/corona-warn-app/cwa-website/pull/3025#issuecomment-1197097660
=> Blog 2.25: Fix URL

cypress/fixtures/copy/stringDe.json, cypress/fixtures/copy/stringEn.json
This PR fixes the cypress test by aligning the texts.
----
Fixes #3115.
=> Fix cypress test (Addresses #3115)

src/data/screenshots.json, src/data/screenshots_de.json, src/data/sitemap.json, src/data/sitemap_de.json
see comments by community members:
1. https://github.com/corona-warn-app/cwa-website/issues/3094#issuecomment-1271477453
2. https://github.com/corona-warn-app/cwa-website/issues/3094#issuecomment-1271488018
---
Internal Tracking ID: [EXPOSUREAPP-14015](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14015)
=> Fix/screenshots 2.26

src/data/analyse_en.json
Internal Tracking ID: [EXPOSUREAPP-14022](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14022)
=> Dashboard: change letter: Pandemic radar (DE) -> Pandemic Radar (DE)

.github/workflows/deploy-master.yml
Due to issue #3162, I create this PR following the correct steps indicated by @MikeMcC399 to solve the similar issue #3160, and therefore solve this problem.
---
Internal Tracking ID: [EXPOSUREAPP-14217](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14217)
=> Update deploy workflow actions to v3

blog/2021-02-23-umfrage-uni-wuppertal/index.md, blog/2021-02-23-umfrage-uni-wuppertal/index_de.md
See issue https://github.com/corona-warn-app/cwa-website/issues/1877
---
Internal Tracking ID: [EXPOSUREAPP-11551](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11551)
=> Update blog: Remove outdated link

src/data/global.json
This PR bumps the copyright year in the footer of the website.
Happy new year! 🎉
This PR should only be merged once a change to any content on the website was done.
---
Internal Tracking ID: [EXPOSUREAPP-14521](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14521)
=> Bump copyright year in footer

src/data/faq.json, src/data/faq_de.json
Thanks for the hint @MikeMcC399 in https://github.com/corona-warn-app/cwa-website/pull/3302#issuecomment-1370914102
=> Fix FAQ #update_faq: Missing target='_blank'

README.md, package-lock.json, package.json
This PR implements the suggestion from https://github.com/corona-warn-app/cwa-website/issues/3313 "Add Markdown-link-check for unchecked Markdown files"
It adds the npm package [markdown-link-check](https://www.npmjs.com/package/markdown-link-check) with a  `checklinks` script to check Markdown source files.
Only `*.md` files in the top-level directory of the cwa-website and the sub-directory `docs` are checked. (Other `*.md` files are used as source files for HTML output and this is checked by the Cypress tests already.)
To check Markdown files execute:
```bash
npm run checklinks
```
An individual Markdown file can also be checked using the npm package [markdown-link-check](https://www.npmjs.com/package/markdown-link-check) directly, for example:
```bash
npx markdown-link-check README.md …
```
=> Add markdown-link-check and checklinks script

science/2021-06-15-science-blog-1/index.md, science/2021-06-15-science-blog-1/index_de.md, science/2021-07-08-science-blog-2/index.md, science/2021-07-08-science-blog-2/index_de.md, science/2021-08-02-science-blog-3/index.md, science/2021-08-02-science-blog-3/index_de.md, science/2021-10-15-science-blog-4/index.md, science/2021-10-15-science-blog-4/index_de.md, science/2022-03-03-science-blog-5/index.md, science/2022-03-03-science-blog-5/index_de.md, science/2022-11-23-science-blog-6/index.md, science/2022-11-23-science-blog-6/index_de.md, src/data/sitemap.json, src/data/sitemap_de.json
- Science blogs are sequentially numbered
- sitemap updated, one blog article was actually missing
- more concise wording of fig captions in science blog 4
Internal Tracking ID: [EXPOSUREAPP-14561](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14561)
=> Science blog numbering and some corrections

src/data/faq.json, src/data/faq_de.json
This PR updates the "updated" dates in #3357 to January 31st, 2023.
---
Internal Tracking ID: [EXPOSUREAPP-14496](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14496)
=> Update TAN FAQ: Change "Updated" date

src/data/global.json, src/data/screenshots-archive-3-0.json, src/data/screenshots-archive-3-0_de.json, src/pages/de/screenshots-archive/3-0.html, src/pages/en/screenshots-archive/3-0.html
As there are currently no new features planned, we're planning to reuse 3.0 screenshots
---
Internal Tracking ID: [EXPOSUREAPP-14513](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14513)
=> Release 3.1 | Update Screenshots

gulpfile.mjs, science/2021-06-15-science-blog-1/index.md, science/2021-06-15-science-blog-1/index_de.md
This PR puts the used videos into the assets/videos directory.
In addition to that, an unused video has been removed.
---
Internal Tracking ID: [EXPOSUREAPP-14829](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14829)
=> Update SB01: Change mp4 path and delete unused video

src/data/faq.json, src/data/faq_de.json
This PR solves #3416. It was partially resolved in #3423, but @MikeMcC399 pointed out two more instances that needed change [here](https://github.com/corona-warn-app/cwa-website/issues/3416#issuecomment-1468417438).
[Glossary EN: European Federation Gateway Service (EFGS)](https://www.coronawarn.app/en/faq/results/#glossary_efgs)
[Glossary DE: European Federation Gateway Service (EFGS)](https://www.coronawarn.app/de/faq/results/#glossary_efgs)
[FAQ EN: How do you guarantee that I remain anonymous when using the Corona-Warn-App?](https://www.coronawarn.app/en/faq/results/#anonymous)
[FAQ DE: Wie ist gewährleistet, dass ich bei der Nutzung der Corona-Warn-App anonym bleibe?](https://www.coronawarn.app/de/faq/results/#anonymous)
---
Internal Tracking ID: …
=> Update FAQ & Glossary regarding EFGS deactivation

src/data/blog.json
Internal Tracking ID: [EXPOSUREAPP-14990](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14990)
=> Update blog.json: Change button text

blog/2023-05-02-funktionsreduzierung/index.md, blog/2023-05-02-funktionsreduzierung/index_de.md, src/data/sitemap.json, src/data/sitemap_de.json
Internal Tracking ID: [EXPOSUREAPP-](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-)
=> Blog May 2, 2023

blog/2023-06-01-danke/index.md, blog/2023-06-01-danke/index_de.md
This PR removes some line breaks from the last blog, to make the blog look nicer and also make it easier to read. It somehow looked off to me before.
=> Remove some linebreaks from last blog

src/data/faq.json, src/data/faq_de.json
See https://github.com/corona-warn-app/cwa-website/issues/3527#issuecomment-1572027136
**EN**
**DE**
=> Update FAQ #international_phone_numbers

CONTRIBUTING.md
=> Add missing words in CONTRIBUTING

src/data/global.json
=> Update global.json: update yellow banner - shutdown of website
